Repository zauberzeug/nicegui, pull requests merged in 2023-06, with the labels that each got.

#967 Providing a nice interface to simplify storing general and user specific data
  .github/workflows/test.yml
  .gitignore
  README.md
  examples/authentication/main.py
  main.py
  nicegui/app.py
  nicegui/element.py
  nicegui/event_listener.py
  nicegui/nicegui.py
  nicegui/run.py
  nicegui/storage.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_storage.py
  website/documentation.py
  website/documentation_tools.py
  website/more_documentation/storage_documentation.py
Labels: enhancement

#984 Extending and enhancing generic events documentation
  main.py
  nicegui/templates/index.html
  website/documentation.py
  website/documentation_tools.py
  website/more_documentation/generic_events_documentation.py
Labels: documentation

#992 Update docs in table.py
  nicegui/elements/table.py
Labels: documentation

#1009 add geolocation demo to demonstrate running async JavaScript
  website/more_documentation/run_javascript_documentation.py
Labels: documentation

#1012 ability to set storage_secret for run_with
  examples/fastapi/frontend.py
  nicegui/helpers.py
  nicegui/run.py
  nicegui/run_with.py
Labels: enhancement

#994 event_handler: allow passing lambdas which call an async func
  nicegui/events.py
  nicegui/functions/refreshable.py
  nicegui/functions/timer.py
  nicegui/helpers.py
  tests/test_events.py
Labels: enhancement

#999 allow passing ui.tab objects into ui.tab_panel
  nicegui/elements/tabs.py
  tests/test_tabs.py
  website/documentation.py
  website/documentation_tools.py
  website/more_documentation/tabs_documentation.py
Labels: enhancement

#1016 Allow streaming of media files and auto-serve local files passed as source for image, interactive_image, video and audio
  .gitignore
  nicegui/app.py
  nicegui/elements/audio.py
  nicegui/elements/image.py
  nicegui/elements/interactive_image.py
  nicegui/elements/mixins/source_element.py
  nicegui/elements/video.py
  nicegui/helpers.py
  poetry.lock
  pyproject.toml
  tests/screen.py
  tests/test_helpers.py
  tests/test_serving_files.py
  website/documentation.py
Labels: enhancement

#1020 do not use python-magic for mime type detection
  nicegui/helpers.py
  poetry.lock
  pyproject.toml
Labels: bug

#1023 avoid treating base64 data as filename
  nicegui/api_router.py
  nicegui/elements/mixins/source_element.py
  nicegui/favicon.py
  nicegui/globals.py
  nicegui/helpers.py
  nicegui/nicegui.py
  nicegui/page.py
  nicegui/run.py
  nicegui/run_with.py
Labels: bug

#1028 Adds drive selector to local_file_picker example on Windows
  examples/local_file_picker/local_file_picker.py
Labels: documentation, enhancement

#1030 ignore events on disabled or hidden elements by default
  nicegui/elements/mixins/disableable_element.py
  nicegui/elements/mixins/visibility.py
  nicegui/events.py
  tests/test_events.py
Labels: enhancement

#1036 provide ui.image demo for base64 data
  website/more_documentation/image_documentation.py
Labels: documentation

#1033 Implement QStepper element
  nicegui/elements/stepper.py
  nicegui/ui.py
  tests/test_stepper.py
  website/documentation.py
  website/more_documentation/stepper_documentation.py
Labels: enhancement

#1076 Fix serving media files from subdirectories
  nicegui/app.py
Labels: bug

#1081 add documentation for ui.separator
  nicegui/elements/separator.py
  website/documentation.py
  website/more_documentation/separator_documentation.py
Labels: documentation

#1082 Ensure move events are only sent between start/end
  nicegui/elements/joystick.py
Labels: bug

#1078 Added log handler demo
  website/more_documentation/log_documentation.py
Labels: documentation

#1085 Only create storage directory if needed
  nicegui/storage.py
Labels: enhancement

#1093 Fix element.run_method('focus')
  nicegui/elements/image.js
  nicegui/elements/input.js
  nicegui/elements/select.js
  nicegui/elements/table.js
  nicegui/elements/upload.js
  nicegui/templates/index.html
  tests/test_input.py
Labels: bug

#1098 Ensure timer runs awaitable
  nicegui/functions/timer.py
  tests/screen.py
  tests/test_timer.py
Labels: enhancement

#1104 Cancel waiting coroutines before enqueueing the next lazy background task
  nicegui/background_tasks.py
  tests/test_storage.py
Labels: bug

#1110 Update conftest.py to avoid deprecation warnings about pytest/selenium
  poetry.lock
  pyproject.toml
  tests/conftest.py
Labels: enhancement
