Repository zauberzeug/nicegui, pull requests merged in 2023-10, with the labels that each got.

#1725 Update ui.icon to have updatable name
  nicegui/elements/icon.py
  nicegui/elements/mixins/name_element.py
Labels: enhancement

#1732 Fix for ctrl-c not closing the pywebview window.
  nicegui/native_mode.py
Labels: bug

#1741 submit audio/video control PR
  nicegui/elements/audio.js
  nicegui/elements/audio.py
  nicegui/elements/video.js
  nicegui/elements/video.py
  website/more_documentation/audio_documentation.py
  website/more_documentation/video_documentation.py
Labels: enhancement

#1734 tests/screen.py race condition fix.
  tests/screen.py
Labels: enhancement

#1747 Add licenses of third-party libraries to Dependencies.md
  DEPENDENCIES.md
  npm.py
Labels: documentation

#1704 Add expand/collapse functions to ui.tree and warn when using the expand_all prop
  nicegui/elements/tree.py
  tests/test_tree.py
  website/more_documentation/tree_documentation.py
Labels: bug

#1754 Warn if notification can not be displayed
  nicegui/functions/notify.py
Labels: enhancement

#1755 ui.table: Use properties to avoid simplify row updates
  nicegui/elements/table.py
  tests/test_table.py
Labels: enhancement

#1760 clarify usage of `ui.open` on auto-index pages
  nicegui/functions/open.py
Labels: documentation

#1759 Simplifying tree example and showing disable feature
  website/more_documentation/tree_documentation.py
Labels: documentation

#1775 Refresh binding before page delivery
  nicegui/binding.py
  nicegui/nicegui.py
  nicegui/page.py
  tests/test_binding.py
Labels: bug

#1781 Introduce `validate()` method for validation elements
  nicegui/elements/mixins/validation_element.py
Labels: enhancement

#1799 Change styles suggestion to style
  website/documentation.py
Labels: documentation

#1812 adapt socket.io heartbeat depending on the provided reconnect_timeout
  main.py
  nicegui/nicegui.py
  nicegui/templates/index.html
Labels: enhancement

#1814 Improve Fly replay middleware to only replay if the target instance is still available
  fly.dockerfile
  main.py
Labels: enhancement

#1801 Introduce `ui.context_menu`
  nicegui/elements/context_menu.py
  nicegui/elements/menu.py
  nicegui/ui.py
  tests/screen.py
  tests/test_context_menu.py
  tests/test_menu.py
  website/documentation.py
  website/more_documentation/context_menu_documentation.py
  website/more_documentation/menu_documentation.py
Labels: enhancement

#1800 element props can be enclosed in double quotes
  nicegui/element.py
  tests/test_element.py
Labels: enhancement

#1824 fixed development docker container
  development.dockerfile
Labels: enhancement

#1823 increased js timeout for search command
  website/search.py
Labels: documentation

#1832 Added LangChain handler to the examples.
  examples/chat_with_ai/log_callback_handler.py
  examples/chat_with_ai/main.py
Labels: documentation

#1856 Replace netifaces with much simpler (and better) ifaddr
  nicegui/welcome.py
  poetry.lock
  pyproject.toml
  release.dockerfile
  website/documentation.py
Labels: enhancement

#1877 Add startup and shutdown handlers to existing FastAPI app
  nicegui/ui_run_with.py
Labels: bug

#1897 make ui.tab_panels can work with other components
  nicegui/elements/tabs.py
Labels: enhancement

#1899 added new element: ui.pagination
  nicegui/elements/pagination.py
  nicegui/ui.py
  tests/test_pagination.py
  website/documentation.py
  website/more_documentation/pagination_documentation.py
Labels: enhancement

#1905 Add an editable table example, getrowids for aggrid
  examples/editable_table/main.py
  main.py
Labels: documentation

#1915 Raise exception if `ui.element` is called with an invalid HTML tag
  nicegui/element.py
  tests/test_element.py
Labels: enhancement

#1914 Support return values of refreshable function
  nicegui/functions/refreshable.py
  tests/test_refreshable.py
Labels: enhancement

#1854 allow binding source with local file paths
  nicegui/elements/mixins/source_element.py
  tests/conftest.py
  tests/screen.py
  tests/test_image.py
Labels: enhancement

#1819 enable new input in select, new-value-mode="add-unique"
  nicegui/elements/select.py
  tests/screen.py
  tests/test_select.py
Labels: enhancement
