Repository zauberzeug/nicegui, pull requests merged in 2023-08, with the labels that each got.

#1276 HTML-encode element text to prevent XSS
  nicegui/client.py
  nicegui/templates/index.html
  tests/test_element.py
Labels: enhancement

#1300 Use fly-replay response header to route websocket connection to correct instance
  main.py
  nicegui/client.py
  nicegui/globals.py
  nicegui/templates/index.html
Labels: bug

#1301 Picking the right "On Air"-instance
  nicegui/air.py
Labels: bug

#1213 Allow creating scene objects without context
  nicegui/elements/scene.py
  nicegui/elements/scene_object3d.py
  tests/test_scene.py
Labels: enhancement

#1315 Add fullscreen property as well as toogle_fullscreen method to Table element
  nicegui/elements/table.py
  website/more_documentation/table_documentation.py
Labels: enhancement

#1313 Fix refreshable with function references
  nicegui/functions/refreshable.py
  tests/test_refreshable.py
Labels: bug

#1309 Warn if ui.open is used before client is connected
  nicegui/client.py
  nicegui/functions/open.py
Labels: enhancement

#1317 Implement line_plot.clear()
  nicegui/elements/line_plot.py
Labels: enhancement

#1255 Additional Docker Features
  docker-entrypoint.sh
  examples/docker_image/README.md
  examples/docker_image/app/main.py
  examples/docker_image/docker-compose.yml
  main.py
  release.dockerfile
  website/documentation.py
Labels: enhancement

#1327 Implement clear method for ui.scene
  nicegui/elements/scene.py
  tests/test_scene.py
Labels: enhancement

#1331 Use a machine-independent Python path instead of "python3"
  examples/script_executor/main.py
Labels: enhancement

#1118 Allow passing local file path to ui.download
  nicegui/app.py
  nicegui/functions/download.py
  tests/conftest.py
  tests/test_download.py
Labels: enhancement

#1238 Added disable context manager demo
  website/more_documentation/button_documentation.py
Labels: documentation

#1353 prevent errors if non-root user already exists
  docker-entrypoint.sh
Labels: enhancement

#1341 added frameless parameter to native mode, also changed NameError to AttributeError
  nicegui/native_mode.py
  nicegui/run.py
Labels: bug, enhancement

#1329 Synchronize scroll padding with header height
  nicegui/page_layout.py
  tests/test_header.py
Labels: enhancement

#1337 Improve On Air reconnect
  nicegui/air.py
Labels: enhancement

#1356 Add on_value_change parameter to ui.expansion
  nicegui/elements/expansion.py
Labels: enhancement

#1359 Add AG Grid column api
  nicegui/elements/aggrid.js
  nicegui/elements/aggrid.py
  tests/test_aggrid.py
  website/more_documentation/aggrid_documentation.py
Labels: enhancement

#1393 Re-use plotly plot if config did not change
  nicegui/elements/plotly.py
  nicegui/elements/plotly.vue
Labels: enhancement

#1402 Add example which generates a pdf
  examples/generate_pdf/.gitignore
  examples/generate_pdf/main.py
  examples/generate_pdf/requirements.txt
  main.py
Labels: documentation

#1201 Support drag and drop for 3D objects in `ui.scene`
  nicegui/elements/lib/three/modules/DragControls.js
  nicegui/elements/scene.js
  nicegui/elements/scene.py
  nicegui/elements/scene_object3d.py
  nicegui/events.py
  npm.json
  website/more_documentation/scene_documentation.py
Labels: enhancement

#1350 Added point dragging to chart element.
  nicegui/elements/chart.js
  nicegui/elements/chart.py
  nicegui/events.py
  website/more_documentation/chart_documentation.py
Labels: enhancement

#1409 Provide method to set options of any choice element (eg. ui.select)
  nicegui/elements/choice_element.py
  tests/screen.py
  tests/test_select.py
  website/more_documentation/select_documentation.py
Labels: enhancement

#1421 Prevent the page from scrolling when closing a dialog
  main.py
  website/static/style.css
Labels: bug

#1419 Disable default aggrid column fit
  nicegui/elements/aggrid.js
  nicegui/elements/aggrid.py
Labels: enhancement

#1437 fix auto_size_columns for aggrid.from_pandas
  nicegui/elements/aggrid.py
Labels: enhancement

#1426 added storage dir path options
  nicegui/globals.py
  nicegui/run.py
  nicegui/run_with.py
  nicegui/storage.py
Labels: enhancement

#1450 Fixed chart events for new hierarchy
  nicegui/events.py
Labels: bug

#1451 ECharts more documentation broken
  main.py
Labels: documentation

#1476 Make storage path configurable via environment variable
  nicegui/globals.py
  nicegui/storage.py
  website/documentation.py
Labels: enhancement

#1473 Color background of color_input
  nicegui/elements/color_input.py
  tests/test_color_input.py
Labels: enhancement

#1478 Allow canceling a timer
  nicegui/functions/timer.py
  tests/test_timer.py
  website/more_documentation/timer_documentation.py
Labels: enhancement

#1470 feat: Implement Ag Grid Dynamic Functions
  nicegui/elements/aggrid.js
  nicegui/static/utils/dynamic_obj.js
  tests/test_aggrid.py
Labels: enhancement

#1498 catch gaierror and improve startup speed
  nicegui/nicegui.py
  nicegui/welcome.py
Labels: enhancement

#1499 Website: ensure search_index.json is not cached between versions
  website/search.py
Labels: enhancement

#1501 adhere forwarded-prefix for redirects
  nicegui/middlewares.py
  nicegui/nicegui.py
  nicegui/storage.py
Labels: bug

#1514 Fix and improve clear, remove and delete methods
  nicegui/binding.py
  nicegui/client.py
  nicegui/element.py
  nicegui/elements/scene.py
  nicegui/elements/upload.py
  nicegui/nicegui.py
  tests/conftest.py
  tests/test_element.py
  tests/test_element_delete.py
  website/documentation.py
Labels: bug
