Repository zauberzeug/nicegui, pull requests merged in 2023-12, with the labels that each got.

#2088 Warn about late returns in @ui.page builder, which were silently dropped before
  nicegui/page.py
  tests/screen.py
  tests/test_page.py
Labels: enhancement

#2108 make ui.open accept NiceGUI element as link target
  nicegui/functions/open.py
Labels: enhancement

#2112 make <em> italics in the documentation
  website/main_page.py
  website/static/style.css
  website/style.py
Labels: documentation

#2110 can specify port even in native mode
  nicegui/ui_run.py
Labels: enhancement

#2127 Allow access to page template head and body
  nicegui/client.py
  nicegui/functions/html.py
Labels: enhancement

#2031 Introduce ui.notification element
  nicegui/element.py
  nicegui/elements/notification.js
  nicegui/elements/notification.py
  nicegui/ui.py
  tests/test_notification.py
  website/documentation/content/notification_documentation.py
  website/documentation/content/section_page_layout.py
Labels: enhancement

#2142 add py.typed so that mypy will not skip checking types against imports from NiceGUI
  nicegui/py.typed
Labels: enhancement

#2147 Improve reconnect when accessing via On Air
  nicegui/templates/index.html
Labels: enhancement

#2154 Update markdown2 dependency
  pyproject.toml
Labels: bug

#2131 Fixed select behavior in case of single with input
  nicegui/elements/select.js
  tests/test_select.py
Labels: bug

#2145 Persistence should handle issues when json data is broken
  nicegui/storage.py
Labels: enhancement

#2183 Introduce CSS variables for default padding and gap
  nicegui/static/nicegui.css
  website/documentation/content/section_styling_appearance.py
Labels: enhancement

#2184 Improve tooltip documentation; make text optional
  nicegui/elements/tooltip.py
  website/documentation/content/section_page_layout.py
  website/documentation/content/tooltip_documentation.py
Labels: documentation, enhancement

#2182 Introduce `ui.page_title`
  nicegui/client.py
  nicegui/functions/page_title.py
  nicegui/ui.py
  tests/test_page_title.py
  website/documentation/content/page_title_documentation.py
  website/documentation/content/section_pages_routing.py
Labels: enhancement

#1217 Leaflet element for interactive maps
  DEPENDENCIES.md
  examples/map/leaflet.js
  examples/map/leaflet.py
  examples/map/main.py
  nicegui/client.py
  nicegui/dependencies.py
  nicegui/element.py
  nicegui/elements/leaflet.js
  nicegui/elements/leaflet.py
  nicegui/elements/leaflet_layer.py
  nicegui/elements/leaflet_layers.py
  nicegui/elements/lib/leaflet/leaflet-draw/images/layers-2x.png
  nicegui/elements/lib/leaflet/leaflet-draw/images/layers.png
  nicegui/elements/lib/leaflet/leaflet-draw/images/marker-icon-2x.png
  nicegui/elements/lib/leaflet/leaflet-draw/images/marker-icon.png
  nicegui/elements/lib/leaflet/leaflet-draw/images/marker-shadow.png
  nicegui/elements/lib/leaflet/leaflet-draw/images/spritesheet-2x.png
  nicegui/elements/lib/leaflet/leaflet-draw/images/spritesheet.png
  nicegui/elements/lib/leaflet/leaflet-draw/images/spritesheet.svg
  nicegui/elements/lib/leaflet/leaflet-draw/leaflet.draw.css
  nicegui/elements/lib/leaflet/leaflet-draw/leaflet.draw.js
  nicegui/elements/lib/leaflet/leaflet/images/layers-2x.png
  nicegui/elements/lib/leaflet/leaflet/images/layers.png
  nicegui/elements/lib/leaflet/leaflet/images/marker-icon-2x.png
  nicegui/elements/lib/leaflet/leaflet/images/marker-icon.png
  nicegui/elements/lib/leaflet/leaflet/images/marker-shadow.png
  nicegui/elements/lib/leaflet/leaflet/leaflet.css
  nicegui/elements/lib/leaflet/leaflet/leaflet.js
  nicegui/elements/lib/leaflet/leaflet/leaflet.js.map
  nicegui/elements/pyplot.py
  nicegui/elements/scene.py
  nicegui/nicegui.py
  nicegui/static/nicegui.css
  nicegui/static/utils/resources.js
  nicegui/ui.py
  npm.json
  npm.py
  tests/test_endpoint_docs.py
  tests/test_leaflet.py
  website/documentation/content/leaflet_documentation.py
  website/documentation/content/section_data_elements.py
  website/examples.py
Labels: enhancement

#2198 Reduce the CSS specificity for ui.link to simplify overriding its style
  nicegui/static/nicegui.css
Labels: enhancement

#2203 Simplify emitting and receiving global events
  nicegui/events.py
  nicegui/functions/on.py
  nicegui/templates/index.html
  nicegui/ui.py
  website/documentation/content/generic_events_documentation.py
Labels: enhancement

#2204 Add class methods to documentation
  nicegui/elements/aggrid.py
  nicegui/elements/table.py
  website/documentation/reference.py
Labels: documentation

#2211 Make text of `ui.expansion` bindable
  nicegui/elements/expansion.py
Labels: enhancement

#2212 Improve warning message for nesting of top level layout elements
  nicegui/page_layout.py
Labels: enhancement

#2218 Allow using `ui.interactive_image` without image
  nicegui/elements/interactive_image.js
  nicegui/elements/interactive_image.py
  website/documentation/content/interactive_image_documentation.py
Labels: enhancement

#2224 Update ui.notification dosctring
  nicegui/elements/notification.py
Labels: documentation

#2217 Replace ui.query's inheritance from ui.element with aggregation
  nicegui/elements/query.py
  nicegui/ui.py
  website/documentation/content/query_documentation.py
Labels: enhancement

#2222 Fixed invalid initialization order
  nicegui/elements/mixins/value_element.py
Labels: enhancement

#2225 Introduce ui.space
  nicegui/elements/space.py
  nicegui/ui.py
  website/documentation/content/section_page_layout.py
  website/documentation/content/space_documentation.py
Labels: enhancement

#2219 doc add vertical tabs example
  website/documentation/content/tabs_documentation.py
Labels: documentation

#2227 ValdationElement.validate now returns a bool
  nicegui/elements/mixins/validation_element.py
  tests/test_input.py
Labels: enhancement

#2162 Add Dynamic Method Call to JSON Editor
  nicegui/elements/aggrid.js
  nicegui/elements/aggrid.py
  nicegui/elements/json_editor.js
  nicegui/elements/json_editor.py
  tests/test_aggrid.py
  tests/test_json_editor.py
  website/documentation/content/aggrid_documentation.py
  website/documentation/content/json_editor_documentation.py
Labels: enhancement

#2233 Migrate storage from system's default encoding to UTF-8
  nicegui/storage.py
  tests/test_storage.py
Labels: enhancement

#2232 Introduce `run_chart_method` for `ui.echart`
  nicegui/elements/echart.js
  nicegui/elements/echart.py
  tests/test_echart.py
  website/documentation/content/echart_documentation.py
Labels: enhancement

#2231 Add support for Plotly events
  nicegui/elements/plotly.vue
  website/documentation/content/plotly_documentation.py
Labels: enhancement

#2235 Bugfix: Default validation dict shared between all instances
  nicegui/elements/input.py
  nicegui/elements/number.py
  nicegui/elements/textarea.py
Labels: enhancement

#2249 Upgrade to newer FastAPI and Starlette versions
  nicegui/client.py
  poetry.lock
  pyproject.toml
Labels: bug

#2133 Adjusting validation element for better err_msg
  nicegui/elements/mixins/validation_element.py
  tests/test_input.py
  website/documentation/content/input_documentation.py
Labels: question

#2191 Allow setting head and body HTML when client is already connected
  nicegui/functions/html.py
  tests/test_add_html.py
Labels: enhancement

#2267 Less strict uvicorn dependency to allow latest versions
  poetry.lock
  pyproject.toml
Labels: enhancement
