Repository zauberzeug/nicegui, pull requests merged in 2023-09, with the labels that each got.

#1605 set min pygments version and update lock
  poetry.lock
  pyproject.toml
Labels: bug

#1617 Website ui.input demo not rendering.
  website/demo.py
  website/more_documentation/aggrid_documentation.py
  website/more_documentation/button_documentation.py
  website/more_documentation/icon_documentation.py
  website/more_documentation/input_documentation.py
  website/more_documentation/number_documentation.py
  website/more_documentation/textarea_documentation.py
Labels: bug

#1581 New example: custom binding
  examples/custom_binding/main.py
  main.py
Labels: documentation

#1635 Interactive image: Fix mousemove event registration
  nicegui/elements/interactive_image.js
  tests/test_interactive_image.py
Labels: bug

#1557 Introducing AuthMiddleware in the authentication example
  examples/authentication/main.py
Labels: documentation

#1537 Get the list of urls on which the server is available
  nicegui/air.py
  nicegui/app.py
  nicegui/events.py
  nicegui/observables.py
  nicegui/storage.py
  nicegui/welcome.py
  tests/test_observables.py
  website/documentation.py
Labels: enhancement

#1646 Table Pagination
  nicegui/elements/table.py
  tests/test_table.py
  website/more_documentation/table_documentation.py
Labels: enhancement

#1579 Echart enhancements - onclick and dynamic options
  nicegui/elements/echart.js
  nicegui/elements/echart.py
  nicegui/events.py
  tests/test_echart.py
  website/more_documentation/echart_documentation.py
Labels: enhancement

#1639 Added the QTimeline element
  nicegui/elements/timeline.py
  nicegui/static/nicegui.css
  nicegui/ui.py
  tests/test_timeline.py
  website/documentation.py
  website/more_documentation/timeline_documentation.py
Labels: enhancement

#1653 Introduce ui.code
  nicegui/elements/code.py
  nicegui/static/nicegui.css
  nicegui/ui.py
  tests/test_code.py
  website/documentation.py
  website/more_documentation/code_documentation.py
Labels: enhancement

#1651 Introduce ui.editor
  nicegui/elements/editor.py
  nicegui/ui.py
  tests/test_editor.py
  website/documentation.py
  website/more_documentation/editor_documentation.py
Labels: enhancement

#1656 Introduce run.cpu_bound and run.io_bound
  examples/ai_interface/main.py
  examples/opencv_webcam/main.py
  examples/progress/main.py
  nicegui/__init__.py
  nicegui/native.py
  nicegui/nicegui.py
  nicegui/run_executor.py
  nicegui/welcome.py
  website/documentation.py
Labels: enhancement

#1662 add NO_NETIFACES env variable for docker releases
  nicegui/welcome.py
  release.dockerfile
  website/documentation.py
Labels: documentation, enhancement

#1661 Support multiple identical header fields in http responses "On Air"
  nicegui/air.py
Labels: enhancement

#1532 Adds basic devcontainer for #1057
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitignore
  CONTRIBUTING.md
  poetry.lock
  pyproject.toml
  tests/conftest.py
Labels: enhancement

#1676 Example: Auth and User Management with Descope
  examples/descope_auth/README.md
  examples/descope_auth/main.py
  examples/descope_auth/requirements.txt
  examples/descope_auth/user.py
  main.py
Labels: documentation
