Repository zauberzeug/nicegui, pull requests merged in 2023-11, with the labels that each got.

#1929 Add inheritance to the modularization example
  examples/modularization/example_c.py
  examples/modularization/example_pages.py
  examples/modularization/home_page.py
  examples/modularization/message.py
  examples/modularization/theme.py
Labels: documentation

#1919 Change AI Chat to page support
  examples/chat_with_ai/main.py
Labels: documentation

#1969 Improve type hints for ui.refreshable
  nicegui/functions/refreshable.py
Labels: enhancement

#1970 Raise RuntimeError if a page layout element is nested
  nicegui/page_layout.py
Labels: enhancement

#1977 Add `force_reload` method for `ui.image` and `ui.interactive_image`
  nicegui/elements/image.js
  nicegui/elements/image.py
  nicegui/elements/interactive_image.js
  nicegui/elements/interactive_image.py
  website/more_documentation/image_documentation.py
  website/more_documentation/interactive_image_documentation.py
Labels: enhancement

#1982 ui.json_editor has no dispose method
  nicegui/elements/json_editor.js
Labels: bug

#1983 UI.table from_pandas method
  nicegui/elements/table.py
  tests/test_table.py
  website/more_documentation/aggrid_documentation.py
  website/more_documentation/table_documentation.py
  website/static/search_index.json
Labels: enhancement

#1997 new example: editable table aggrid
  examples/editable_ag_grid/main.py
  main.py
  website/static/search_index.json
Labels: documentation

#2006 Fix draggable object deletion
  nicegui/elements/scene.js
Labels: bug

#1952 integer argument for ui.number
  nicegui/elements/number.py
  tests/test_number.py
  website/more_documentation/number_documentation.py
Labels: enhancement

#2057 Some intro text for the new Documentation start page
  website/documentation/content.py
Labels: documentation

#2050 Allow client to download raw data from server
  nicegui/client.py
  nicegui/functions/download.py
  nicegui/templates/index.html
  tests/test_download.py
Labels: enhancement

#2068 Fix update of echart options when number of series changes
  nicegui/elements/echart.js
Labels: bug

#2069 Support PIL images as image source
  nicegui/elements/image.py
  nicegui/elements/interactive_image.py
  website/documentation/more/image_documentation.py
Labels: enhancement
