Repository zauberzeug/nicegui, pull requests merged in 2023-07, with the labels that each got.

#1119 add on_change parameter for ui.knob
  nicegui/elements/knob.py
Labels: enhancement

#1120 Demo removing default padding with query selector
  nicegui/elements/query.py
  website/more_documentation/query_documentation.py
Labels: documentation

#1137 Find IP addresses more robustly using netifaces
  nicegui/helpers.py
  nicegui/nicegui.py
  poetry.lock
  pyproject.toml
Labels: bug

#1139 Fix two favicon issues
  nicegui/favicon.py
Labels: bug

#1122 Fixed table selection not going away after removing selection in table_and_slots example
  nicegui/elements/table.py
  tests/test_table.py
Labels: bug, documentation

#1143 Lighter core package by making pywebview, plotly and matplotlib optional
  .github/workflows/test.yml
  development.dockerfile
  nicegui/globals.py
  nicegui/native_mode.py
  nicegui/ui.py
  poetry.lock
  pyproject.toml
  website/documentation.py
Labels: enhancement

#1134 using hierarchical path names to identify JS dependencies
  examples/custom_vue_component/counter.py
  examples/custom_vue_component/main.py
  examples/map/leaflet.py
  examples/single_page_app/router.py
  nicegui/client.py
  nicegui/dependencies.py
  nicegui/element.py
  nicegui/elements/aggrid.py
  nicegui/elements/audio.py
  nicegui/elements/chart.py
  nicegui/elements/chat_message.py
  nicegui/elements/choice_element.py
  nicegui/elements/colors.py
  nicegui/elements/dark_mode.py
  nicegui/elements/image.py
  nicegui/elements/input.py
  nicegui/elements/interactive_image.py
  nicegui/elements/joystick.py
  nicegui/elements/keyboard.py
  nicegui/elements/link.py
  nicegui/elements/log.py
  nicegui/elements/markdown.js
  nicegui/elements/markdown.py
  nicegui/elements/mermaid.js
  nicegui/elements/mermaid.py
  nicegui/elements/plotly.py
  nicegui/elements/query.py
  nicegui/elements/scene.py
  nicegui/elements/select.py
  nicegui/elements/table.py
  nicegui/elements/textarea.py
  nicegui/elements/upload.py
  nicegui/elements/video.py
  nicegui/functions/refreshable.py
  nicegui/nicegui.py
  nicegui/templates/index.html
  tests/test_aggrid.py
  tests/test_chart.py
  tests/test_mermaid.py
  tests/test_plotly.py
  tests/test_scene.py
  website/intersection_observer.py
Labels: enhancement

#1166 Make `netifaces` dependency optional
  nicegui/helpers.py
  nicegui/nicegui.py
  nicegui/welcome.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#1176 Introduce a carousel element
  nicegui/elements/carousel.py
  nicegui/ui.py
  tests/test_carousel.py
  website/documentation.py
  website/more_documentation/carousel_documentation.py
Labels: enhancement

#1079 Added functions to get client data to AgGrid element
  nicegui/elements/aggrid.py
Labels: enhancement

#1164 Dark mode for NiceGUI documentation
  main.py
  nicegui/elements/dark_mode.js
  nicegui/elements/dark_mode.py
  nicegui/elements/markdown.py
  website/demo.py
  website/documentation.py
  website/example_card.py
  website/more_documentation/dark_mode_documentation.py
  website/static/style.css
  website/style.py
Labels: documentation

#1190 Resize scene canvas and text renderers with container div
  nicegui/elements/scene.js
  website/more_documentation/scene_documentation.py
Labels: enhancement

#1236 Change link to material icons
  nicegui/elements/icon.py
Labels: documentation

#1239 add demo for tree expansion/collapse
  website/more_documentation/tree_documentation.py
Labels: documentation

#1262 allow configuration of socket.io transport options
  main.py
  nicegui/client.py
  nicegui/globals.py
  nicegui/templates/index.html
Labels: bug, documentation

#1243 Support `ui.open` with new tab
  nicegui/client.py
  nicegui/functions/open.py
  nicegui/templates/index.html
  tests/test_open.py
Labels: enhancement

#1266 Refactor optional feature handling to preserve signature of ui.plotly etc.
  nicegui/elements/plotly.py
  nicegui/elements/pyplot.py
  nicegui/ui.py
Labels: enhancement

#1272 Add demos to use image links
  website/more_documentation/image_documentation.py
  website/more_documentation/link_documentation.py
Labels: documentation

#1273 add demo "download text as file"
  examples/download_text_as_file/main.py
  main.py
Labels: documentation
