Repository zauberzeug/nicegui, pull requests merged in 2023-05, with the labels that each got.

#857 #848 Use `root_path` as prefix
  nicegui/client.py
Labels: enhancement

#851 Pandas dataframe example
  examples/pandas_dataframe/main.py
  main.py
Labels: documentation

#850 Adding New Binding Documentation Examples
  main.py
  website/demo.py
  website/documentation.py
  website/documentation_tools.py
  website/more_documentation/bindings_documentation.py
Labels: documentation

#880 introduce element.move()
  nicegui/element.py
  tests/test_element.py
  website/more_documentation/element_documentation.py
Labels: enhancement

#886 improved discoverability for "more docs"
  website/documentation_tools.py
Labels: documentation, enhancement

#881 Chat message improvements
  nicegui/elements/chat_message.js
  nicegui/elements/chat_message.py
  tests/test_chat.py
  website/more_documentation/chat_message_documentation.py
Labels: enhancement

#877 fix grabbing client ip from sio environ
  nicegui/client.py
Labels: bug

#887 Add background demo to ui.query
  website/more_documentation/query_documentation.py
Labels: documentation

#876 add markdown tables demo + improved styling
  nicegui/static/nicegui.css
  website/more_documentation/markdown_documentation.py
Labels: documentation

#888 Move detailed page documentation to "more"
  website/documentation.py
  website/more_documentation/page_documentation.py
Labels: documentation

#822 Add sqlite CRUD example
  examples/sqlite_database/.gitignore
  examples/sqlite_database/main.py
  main.py
Labels: documentation

#900 Ignore socket failures and just use localhost
  nicegui/nicegui.py
Labels: bug

#914 New demo to show multi line notifications
  website/more_documentation/notify_documentation.py
Labels: documentation

#933 add icon demo for ui.button
  website/more_documentation/button_documentation.py
Labels: documentation

#941 add demo for masonry layout
  website/more_documentation/column_documentation.py
Labels: documentation

#950 demo for reacting on content changes via binding
  website/more_documentation/label_documentation.py
Labels: documentation

#955 Add SimPy example
  .github/workflows/test.yml
  examples/simpy/async_realtime_environment.py
  examples/simpy/main.py
  examples/simpy/requirements.txt
Labels: documentation

#968 Add Lightbox example
  examples/lightbox/main.py
  main.py
Labels: documentation

#917 Call native window methods from NiceGUI main thread
  nicegui/native.py
  nicegui/native_mode.py
  nicegui/nicegui.py
  nicegui/run.py
  website/documentation.py
Labels: enhancement

#964 Allow using NiceGUI elements as link targets and adding demos to the documentation
  nicegui/elements/link.py
  tests/test_link.py
  website/demo.py
  website/more_documentation/link_documentation.py
Labels: documentation, enhancement

#963 Fixed and improved favicon routing
  .github/workflows/test.yml
  nicegui/favicon.py
  nicegui/nicegui.py
  tests/conftest.py
  tests/requirements.txt
  tests/screen.py
  tests/test_favicon.py
Labels: bug
