Repository zauberzeug/nicegui, pull requests merged in 2024-10, with the labels that each got.

#3545 Faster creation of monochrome point clouds
  nicegui/elements/scene.js
  nicegui/elements/scene_object3d.py
  nicegui/elements/scene_objects.py
Labels: enhancement

#3839 Improve logging for On Air connections
  nicegui/air.py
Labels: enhancement

#3829 Check value of choice elements against options
  .github/dependabot.yml
  nicegui/elements/choice_element.py
  tests/test_select.py
Labels: enhancement

#3853 Expose additional PyInstaller arguments
  nicegui/scripts/pack.py
Labels: enhancement

#3865 Add Cache-Control header to static files
  nicegui/app/app.py
  nicegui/nicegui.py
  nicegui/staticfiles.py
  tests/test_serving_files.py
Labels: enhancement

#3860 Add demo about LaTeX formulas in `ui.markdown`
  .devcontainer/Dockerfile
  development.dockerfile
  fly.dockerfile
  release.dockerfile
  website/documentation/content/markdown_documentation.py
Labels: documentation

#3848 Allow customizing the crosshair in `ui.interactive_image`
  nicegui/elements/interactive_image.js
  website/documentation/content/interactive_image_documentation.py
Labels: enhancement

#3868 doc storage small update re: duplicated tabs
  website/documentation/content/storage_documentation.py
Labels: documentation

#3866 Run dynamic argument conversion when using run_grid_method / run_row_method
  nicegui/elements/aggrid.js
Labels: enhancement

#3843 Define default classes while subclassing
  nicegui/element.py
  nicegui/elements/aggrid.py
  nicegui/elements/card.py
  nicegui/elements/carousel.py
  nicegui/elements/code.py
  nicegui/elements/codemirror.py
  nicegui/elements/column.py
  nicegui/elements/echart.py
  nicegui/elements/editor.py
  nicegui/elements/expansion.py
  nicegui/elements/grid.py
  nicegui/elements/joystick.py
  nicegui/elements/leaflet.py
  nicegui/elements/link.py
  nicegui/elements/log.py
  nicegui/elements/markdown.py
  nicegui/elements/pyplot.py
  nicegui/elements/row.py
  nicegui/elements/scene.py
  nicegui/elements/scene_view.py
  nicegui/elements/scroll_area.py
  nicegui/elements/separator.py
  nicegui/elements/splitter.py
  nicegui/elements/stepper.py
  nicegui/elements/tabs.py
  nicegui/elements/timeline.py
  nicegui/page_layout.py
  nicegui/testing/general_fixtures.py
Labels: bug

#3896 Improve startup tests
  test_startup.sh
Labels: enhancement

#3893 Pipeline improvements
  .github/workflows/publish.yml
  .github/workflows/test.yml
  examples/authentication/conftest.py
  examples/authentication/test_authentication.py
  examples/chat_app/conftest.py
  examples/chat_app/main.py
  examples/chat_app/test_chat_app.py
  examples/todo_list/conftest.py
  examples/todo_list/test_todo_list.py
  pyproject.toml
  release.dockerfile
Labels: github_actions, docker

#3876 Improve generation of unique tab IDs
  nicegui/air.py
  nicegui/nicegui.py
  nicegui/static/nicegui.js
  nicegui/storage.py
Labels: bug

#3902 Set selection, expansion and tick props for `ui.tree` only when needed
  nicegui/elements/tree.py
Labels: enhancement

#3913 Add better info about how to write a complete test
  website/documentation/content/user_documentation.py
Labels: documentation

#3906 Add sponsor section to website
  README.md
  fetch_sponsors.py
  website/main_page.py
  website/sponsors.json
  website/sponsors.py
Labels: documentation

#3918 Fix docker cache in github actions
  .github/workflows/publish.yml
Labels: bug

#3900 Introduce an `html` module with plain HTML elements
  nicegui/__init__.py
  nicegui/html.py
  tests/test_html.py
  website/documentation/content/section_text_elements.py
Labels: enhancement

#3895 Show warning when force_reload is used on data sources
  nicegui/elements/image.py
  nicegui/elements/interactive_image.py
  tests/test_image.py
Labels: enhancement
