Repository zauberzeug/nicegui, pull requests merged in 2024-05, with the labels that each got.

#2942 Add chip element
  .vscode/settings.json
  nicegui/elements/chip.py
  nicegui/elements/mixins/selectable_element.py
  nicegui/ui.py
  tests/test_chip.py
  website/documentation/content/chip_documentation.py
  website/documentation/content/section_controls.py
Labels: enhancement

#2990 Documentation: Fix a broken link on the ui.page documentation
  website/documentation/content/page_documentation.py
Labels: documentation

#3010 Add more documentation for `ui.keyboard`
  nicegui/elements/keyboard.py
Labels: documentation

#2964 Improve devcontainer experience
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  poetry.lock
  pyproject.toml
Labels: enhancement

#2947 Scene view component
  nicegui/elements/scene_view.js
  nicegui/elements/scene_view.py
  nicegui/ui.py
  tests/test_scene_view.py
  website/documentation/content/scene_documentation.py
Labels: enhancement

#3008 Add quasar's "row" class to `ui.row`
  nicegui/elements/column.py
  nicegui/elements/row.py
Labels: enhancement

#3022 Improve performance of 3D scenes by initializing all objects at once
  nicegui/elements/scene.js
  nicegui/elements/scene.py
  nicegui/elements/scene_object3d.py
Labels: enhancement

#3032 fix: add missing comma
  nicegui/ui.py
Labels: bug

#3046 Implement __copy__ for observable collections (fixes #3023)
  nicegui/observables.py
  tests/test_observables.py
  tests/test_storage.py
Labels: bug

#2983 Raise Exception when awaiting JavaScript on auto-index page
  nicegui/client.py
  nicegui/elements/notification.js
  nicegui/elements/notification.py
  tests/test_aggrid.py
  tests/test_clipboard.py
  tests/test_codemirror.py
  tests/test_echart.py
  tests/test_javascript.py
  tests/test_json_editor.py
  tests/test_lifecycle.py
  website/documentation/content/clipboard_documentation.py
Labels: bug

#3056 Initialization animation failure in ECharts
  nicegui/elements/echart.js
  tests/test_echart.py
Labels: bug

#3089 Make `ui.code` a ContentElement to support binding
  nicegui/elements/code.py
Labels: enhancement

#3090 Add example to subscribe to audio events
  website/documentation/content/audio_documentation.py
Labels: documentation

#3097 Add yield state in main app lifespan
  nicegui/ui_run_with.py
Labels: enhancement

#3108 fix: fix nginx_subpath example by add proxy_redirect
  examples/nginx_subpath/nginx.conf
Labels: bug

#3118 Use local files for testing `ui.interactive_image`
  .gitignore
  nicegui/testing/screen.py
  tests/media/.gitignore
  tests/media/test1.jpg
  tests/media/test2.jpg
  tests/test_interactive_image.py
Labels: enhancement

#3113 Only ignore specific missing imports with mypy
  nicegui/elements/mixins/value_element.py
  nicegui/events.py
  nicegui/observables.py
  pyproject.toml
  website/documentation/content/audio_documentation.py
Labels: enhancement

#3125 Prevent `ui.leaflet` from flickering after calling `flyTo()`
  nicegui/elements/leaflet.js
  nicegui/elements/leaflet.py
Labels: bug

#3123 Warn about communication attempts with disconnected clients
  nicegui/client.py
  nicegui/outbox.py
Labels: enhancement

#3130 Allow commas in unquoted prop strings
  nicegui/element.py
  tests/test_element.py
Labels: enhancement

#3138 Add encoding of generated URLs
  nicegui/app/app.py
Labels: bug
