Repository zauberzeug/nicegui, pull requests merged in 2024-02, with the labels that each got.

#2494 Introduce media_type parameter for `ui.download`
  nicegui/client.py
  nicegui/functions/download.py
  nicegui/templates/index.html
Labels: enhancement

#2506 Relaxe upper bounds on some dependencies
  pyproject.toml
Labels: enhancement

#2505 Register plotly event handlers only once, at mount
  nicegui/elements/plotly.vue
Labels: bug

#2521 Strip root_path to make ASGIServer from socketio compatible with mounting as sub-app
  examples/fastapi/frontend.py
  nicegui/nicegui.py
Labels: bug

#2527 Introduce `ui.list`, `ui.item`, `ui.item_section` and `ui.item_label`
  nicegui/elements/list.py
  nicegui/ui.py
  tests/test_list.py
  website/documentation/content/list_documentation.py
  website/documentation/content/section_page_layout.py
Labels: enhancement

#2539 Add tooltips to the search and theme buttons.
  website/header.py
  website/search.py
Labels: documentation

#2544 Fix binding removal for non-hashable objects
  nicegui/binding.py
  nicegui/client.py
  nicegui/elements/leaflet.py
  nicegui/elements/scene.py
Labels: bug

#2547 When searching we can now see a snippet of the content of each result.
  website/search.py
Labels: documentation, enhancement

#2564 Provide infos about our coding style
  CONTRIBUTING.md
Labels: documentation

#2546 Add On Air support for ui.run_with
  nicegui/ui_run_with.py
Labels: enhancement

#2569 python-multipart vulnerable to Content-Type Header ReDoS
  poetry.lock
  pyproject.toml
Labels: enhancement

#2572 Add sponsor button to the website
  website/documentation/content/overview.py
Labels: documentation

#2557 Leaflet.js & .py: fixed layer events and run_layer_method
  nicegui/elements/leaflet.js
Labels: bug

#2532 Support GLTF meshes in `ui.scene` elements
  nicegui/elements/lib/three/modules/BufferGeometryUtils.js
  nicegui/elements/lib/three/modules/GLTFLoader.js
  nicegui/elements/scene.js
  nicegui/elements/scene.py
  nicegui/elements/scene_objects.py
  npm.json
  npm.py
  tests/test_scene.py
  website/documentation/content/scene_documentation.py
Labels: enhancement

#2603 Fix order of removing elements when client disconnects
  nicegui/client.py
Labels: bug

#2610 Support other tags than div for ui.html
  nicegui/elements/html.py
  website/documentation/content/html_documentation.py
Labels: enhancement

#2607 Use more specific page titles for individual documentation pages
  website/documentation/rendering.py
Labels: documentation

#2615 Add a toggleable button demo to the docs
  website/documentation/content/button_documentation.py
Labels: documentation

#2606 Allow awaiting the "init" event of `ui.map` and `ui.scene`
  nicegui/elements/leaflet.py
  nicegui/elements/scene.py
  website/documentation/content/leaflet_documentation.py
  website/documentation/content/scene_documentation.py
Labels: enhancement

#2624 docutils is required by ui.restructured_text
  poetry.lock
  pyproject.toml
Labels: bug
