Repository zauberzeug/nicegui, pull requests merged in 2024-07, with the labels that each got.

#3309 Teleport Example
  website/documentation/content/teleport_documentation.py
Labels: documentation

#3329 Fix link to tabs-panel
  website/documentation/content/tabs_documentation.py
Labels: documentation

#3328 Enforce amd64 platform for devcontainer to fix chromedriver on Mac
  .devcontainer/Dockerfile
Labels: bug

#3327 Add pytest-watcher dev dependency
  poetry.lock
  pyproject.toml
Labels: enhancement

#3310 Fix misleading error message if storage secret is set
  nicegui/client.py
  nicegui/storage.py
  tests/test_storage.py
Labels: bug

#3333 Add documentation about BindableProperties
  website/documentation/content/section_binding_properties.py
Labels: documentation

#3319 Support named slots in Element.move
  nicegui/element.py
  tests/test_element.py
  website/documentation/content/element_documentation.py
Labels: enhancement

#3338 Update tooltip documentation: clarify method limitations and add upload component example
  website/documentation/content/tooltip_documentation.py
Labels: documentation

#3320 shutdown with SIGINT if autoreload is enabled
  nicegui/app/app.py
Labels: enhancement

#3362 Add info about failing pre-commit hook
  CONTRIBUTING.md
Labels: documentation

#3381 Fix typing for ElementFilter and User
  nicegui/element_filter.py
  nicegui/testing/user.py
  nicegui/testing/user_interaction.py
  tests/test_element_filter.py
  tests/test_user_simulation.py
Labels: enhancement

#3382 Implement full `ui.navigate` functionality for user simulation
  nicegui/functions/navigate.py
  nicegui/testing/fixtures.py
  nicegui/testing/user.py
  nicegui/testing/user_navigate.py
  nicegui/ui.py
  tests/test_user_simulation.py
Labels: enhancement

#3383 Make combining multiple content filters more robust
  nicegui/element_filter.py
  tests/test_user_simulation.py
Labels: enhancement

#3390 Improve notes about contributing
  CONTRIBUTING.md
Labels: documentation

#3389 Update `ui.number` after sanitization
  nicegui/elements/number.py
  tests/test_number.py
Labels: bug

#3346 Fix value updates in ui.editor after client-side changes
  nicegui/elements/editor.js
  nicegui/elements/editor.py
  tests/test_editor.py
Labels: bug

#3396 Allow pretty printing storage json
  nicegui/json/builtin_wrapper.py
  nicegui/json/orjson_wrapper.py
  nicegui/storage.py
  website/documentation/content/storage_documentation.py
Labels: enhancement

#3409 Improve the documentation overview
  website/documentation/content/overview.py
Labels: documentation

#3417 Restrict access to all routes (except /_nicegui)
  examples/authentication/main.py
Labels: documentation, enhancement
