Repository zauberzeug/nicegui, pull requests merged in 2024-09, with the labels that each got.

#3663 Clear storage dir after test completion
  nicegui/storage.py
  nicegui/testing/general_fixtures.py
Labels: enhancement

#3549 Allow draggable groups
  nicegui/elements/lib/three/modules/DragControls.js
  nicegui/elements/scene.js
  npm.py
Labels: bug

#3679 add debug logs for on air reconnects
  nicegui/air.py
Labels: enhancement

#3678 Add demo showing how to only react to user interactions
  website/documentation/content/checkbox_documentation.py
  website/documentation/content/switch_documentation.py
Labels: documentation

#3689 Introduce proper download simulation for the user fixture
  nicegui/testing/user.py
  nicegui/testing/user_download.py
  tests/test_user_simulation.py
  website/documentation/content/user_documentation.py
Labels: enhancement

#3544 Fix orbit controls of `ui.scene` after changing the camera's up vector
  nicegui/elements/scene.js
Labels: bug

#3547 Add coordinate_system object
  nicegui/elements/scene.js
  nicegui/elements/scene.py
  nicegui/elements/scene_objects.py
  website/documentation/content/scene_documentation.py
Labels: enhancement

#3697 Add dark_page props to ui.colors
  nicegui/elements/colors.js
  nicegui/elements/colors.py
Labels: enhancement

#3709 Remove non-existent flag from `docker compose down` command in docker.sh
  docker.sh
Labels: enhancement

#3731 improve the document of storage
  website/documentation/content/storage_documentation.py
Labels: documentation

#3736 Fix for ChoiceElement duplicate `self.update()` calls and basic ChoiceElement unit testing
  nicegui/elements/choice_element.py
  tests/test_radio_element.py
Labels: enhancement

#3703 Correct doc of `run_chart_method`.
  nicegui/elements/echart.py
Labels: documentation

#3765 Allow testing for validation texts
  nicegui/element_filter.py
  tests/test_user_simulation.py
Labels: enhancement

#3708 Custom colors prop support
  nicegui/elements/colors.js
  nicegui/elements/colors.py
  website/documentation/content/colors_documentation.py
Labels: enhancement

#3750 Simplify clearing of values in pytests with simulated user interaction
  nicegui/testing/user_interaction.py
  tests/test_user_simulation.py
Labels: enhancement

#3699 Handle type error when navigating
  nicegui/functions/navigate.py
Labels: enhancement

#3698 Improve error message when client is not yet initialised
  nicegui/testing/user.py
Labels: enhancement

#3791 Improve conversion of dynamic props
  nicegui/static/nicegui.js
  nicegui/static/utils/dynamic_properties.js
Labels: enhancement

#3792 Serve codehilite CSS for `ui.markdown` more efficiently
  nicegui/element.py
  nicegui/elements/markdown.js
  nicegui/elements/markdown.py
  tests/test_endpoint_docs.py
Labels: enhancement

#3789 Support radio button in ElementFilter
  nicegui/element_filter.py
  tests/test_element_filter.py
Labels: enhancement

#3804 Install sass for fly.io hosted docs
  fly.dockerfile
Labels: bug

#3798 Make On Air reconnects more robust
  nicegui/air.py
Labels: enhancement

#3811 Add handler type alias and use it in event handlers
  nicegui/element.py
  nicegui/elements/button.py
  nicegui/elements/button_dropdown.py
  nicegui/elements/carousel.py
  nicegui/elements/checkbox.py
  nicegui/elements/chip.py
  nicegui/elements/choice_element.py
  nicegui/elements/codemirror.py
  nicegui/elements/color_input.py
  nicegui/elements/color_picker.py
  nicegui/elements/dark_mode.py
  nicegui/elements/date.py
  nicegui/elements/echart.py
  nicegui/elements/editor.py
  nicegui/elements/expansion.py
  nicegui/elements/input.py
  nicegui/elements/interactive_image.py
  nicegui/elements/item.py
  nicegui/elements/joystick.py
  nicegui/elements/json_editor.py
  nicegui/elements/keyboard.py
  nicegui/elements/knob.py
  nicegui/elements/menu.py
  nicegui/elements/mixins/selectable_element.py
  nicegui/elements/mixins/value_element.py
  nicegui/elements/notification.py
  nicegui/elements/number.py
  nicegui/elements/pagination.py
  nicegui/elements/radio.py
  nicegui/elements/range.py
  nicegui/elements/scene.py
  nicegui/elements/scene_view.py
  nicegui/elements/scroll_area.py
  nicegui/elements/select.py
  nicegui/elements/slider.py
  nicegui/elements/splitter.py
  nicegui/elements/stepper.py
  nicegui/elements/switch.py
  nicegui/elements/table.py
  nicegui/elements/tabs.py
  nicegui/elements/textarea.py
  nicegui/elements/time.py
  nicegui/elements/toggle.py
  nicegui/elements/tree.py
  nicegui/elements/upload.py
  nicegui/events.py
  nicegui/functions/on.py
  tests/test_radio_element.py
  website/documentation/content/storage_documentation.py
Labels: enhancement
