Repository zauberzeug/nicegui, pull requests merged in 2024-03, with the labels that each got.

#2655 Add demo for altering the number of steps in a ui.stepper
  website/documentation/content/stepper_documentation.py
Labels: documentation

#2659 Introduce ui.navigate.reload()
  nicegui/functions/navigate.py
Labels: enhancement

#2661 Allow disabling the auto-validation on value change
  nicegui/elements/input.py
  nicegui/elements/mixins/validation_element.py
  nicegui/elements/number.py
  nicegui/elements/select.py
  nicegui/elements/textarea.py
  tests/test_select.py
Labels: enhancement

#2467 Enable new_value_mode="add" for dict options
  .vscode/settings.json
  nicegui/elements/select.py
  tests/test_select.py
Labels: enhancement

#2686 New `ui.log` implementation
  nicegui/elements/log.js
  nicegui/elements/log.py
  nicegui/static/nicegui.css
  tests/test_log.py
Labels: bug

#2685 Add new example with global computation and progress bar
  examples/global_worker/main.py
  website/examples.py
Labels: documentation

#2702 Reduce payload
  nicegui/element.py
  nicegui/templates/index.html
Labels: enhancement

#2623 Add webserial demo
  examples/webserial/main.py
  examples/webserial/script.js
  examples/webserial/sketch/sketch.ino
  website/examples.py
Labels: documentation

#2531 Introduce `ui.add_style` for CSS, SASS and SCSS
  examples/chat_app/main.py
  examples/chat_with_ai/main.py
  nicegui/functions/style.py
  nicegui/ui.py
  poetry.lock
  pyproject.toml
  tests/test_add_html.py
  website/documentation/content/add_style_documentation.py
  website/documentation/content/doc/api.py
  website/documentation/content/section_styling_appearance.py
  website/documentation/rendering.py
  website/star.py
Labels: enhancement

#2707 docs: enhance macos packaging instructions
  website/documentation/content/section_configuration_deployment.py
Labels: documentation

#2728 Extract nicegui.js to allow browser caching
  nicegui/static/nicegui.js
  nicegui/templates/index.html
Labels: enhancement

#2727 Support colored crosshairs for ui.interactive_image
  nicegui/elements/interactive_image.js
  nicegui/elements/interactive_image.py
  website/documentation/content/interactive_image_documentation.py
Labels: enhancement

#2716 Add support for additional echart events
  nicegui/elements/echart.js
  tests/test_echart.py
  website/documentation/content/echart_documentation.py
Labels: enhancement

#2701 Add support for custom row and column templates for ui.grid
  nicegui/elements/grid.py
  website/documentation/content/grid_documentation.py
Labels: enhancement

#2705 Allow passing functions to `run_method` calls
  nicegui/elements/aggrid.js
  nicegui/elements/echart.js
  nicegui/elements/json_editor.js
  nicegui/elements/leaflet.js
  nicegui/static/nicegui.js
  tests/test_aggrid.py
  website/documentation/content/aggrid_documentation.py
Labels: enhancement

#2746 implement static files serving without app.mount
  nicegui/app/app.py
  tests/test_serving_files.py
Labels: bug

#2733 run io_bound and cpu_bound maintain type signatures of their callbacks
  nicegui/run.py
Labels: enhancement

#2753 Update ui.number after changing its limits
  nicegui/elements/number.py
  nicegui/static/nicegui.js
  tests/test_number.py
Labels: bug

#2762 Add range control
  nicegui/elements/range.py
  nicegui/ui.py
  tests/test_range.py
  website/documentation/content/range_documentation.py
  website/documentation/content/section_controls.py
Labels: enhancement

#2708 Event registration, continued :)
  examples/fullcalendar/fullcalendar.py
  nicegui/client.py
  nicegui/elements/button.py
  nicegui/elements/color_picker.py
  nicegui/elements/echart.py
  nicegui/elements/interactive_image.py
  nicegui/elements/joystick.py
  nicegui/elements/json_editor.py
  nicegui/elements/keyboard.py
  nicegui/elements/list.py
  nicegui/elements/menu.py
  nicegui/elements/mixins/value_element.py
  nicegui/elements/scene.py
  nicegui/elements/scroll_area.py
  nicegui/elements/table.py
  nicegui/elements/tree.py
  nicegui/elements/upload.py
Labels: enhancement

#2761 More elegant way to terminate On Air connection
  nicegui/air.py
Labels: enhancement

#2704 Allow registering click and value change events after element instantiation
  examples/fullcalendar/fullcalendar.py
  nicegui/client.py
  nicegui/elements/button.py
  nicegui/elements/color_picker.py
  nicegui/elements/echart.py
  nicegui/elements/interactive_image.py
  nicegui/elements/joystick.py
  nicegui/elements/json_editor.py
  nicegui/elements/keyboard.py
  nicegui/elements/list.py
  nicegui/elements/menu.py
  nicegui/elements/mixins/value_element.py
  nicegui/elements/scene.py
  nicegui/elements/scroll_area.py
  nicegui/elements/table.py
  nicegui/elements/tree.py
  nicegui/elements/upload.py
Labels: enhancement

#2745 Add pointer events to interactive image
  nicegui/elements/interactive_image.js
  nicegui/elements/interactive_image.py
  website/documentation/content/interactive_image_documentation.py
Labels: enhancement

#2756 Fix jumping cursor for `ui.editor`
  nicegui/elements/editor.py
  nicegui/elements/mixins/value_element.py
Labels: bug

#2765 Adding upload_all argument for upload element
  nicegui/elements/upload.py
  nicegui/events.py
  tests/test_upload.py
Labels: enhancement
