Repository zauberzeug/nicegui, pull requests merged in 2024-11, with the labels that each got.

#3947 Add demo to show how to setup submenus
  website/documentation/content/menu_documentation.py
Labels: documentation

#3963 add missing space in storage docs
  website/documentation/content/storage_documentation.py
Labels: documentation

#3969 Integrating Polars into ui.table and ui.aggrid
  nicegui/elements/aggrid.py
  nicegui/elements/table.py
  nicegui/optional_features.py
  poetry.lock
  pyproject.toml
  tests/test_aggrid.py
  tests/test_table.py
  website/documentation/content/aggrid_documentation.py
  website/documentation/content/table_documentation.py
Labels: enhancement

#3993 Add Python 3.13 to test workflow
  .github/workflows/test.yml
  poetry.lock
  pyproject.toml
Labels: github_actions

#3996 Add code check pipeline
  .github/workflows/test.yml
  .vscode/settings.json
  nicegui/elements/pyplot.py
  nicegui/native/native.py
  poetry.lock
  pyproject.toml
Labels: github_actions

#3994 Show warning when `ui.dark_mode` breaks Tailwind
  nicegui/elements/dark_mode.py
Labels: bug

#4019 Allow toggling classes
  nicegui/classes.py
  nicegui/element.py
  nicegui/elements/query.py
  tests/test_element.py
Labels: enhancement

#4018 Allow ungrouping 3D objects
  nicegui/elements/scene.js
  nicegui/elements/scene_object3d.py
  website/documentation/content/scene_documentation.py
Labels: enhancement

#4001 Add ui.input trigger autocomplete trigger capability
  nicegui/testing/user_interaction.py
  tests/test_user_simulation.py
  website/documentation/content/user_documentation.py
Labels: enhancement

#4024 Add support for async validation functions
  nicegui/elements/input.py
  nicegui/elements/mixins/validation_element.py
  nicegui/elements/number.py
  nicegui/elements/select.py
  tests/test_input.py
  website/documentation/content/input_documentation.py
Labels: enhancement

#4032 Add 'max_cache_age' parameter to 'add_static_files' and 'add_static_file'.
  nicegui/app/app.py
  nicegui/staticfiles.py
Labels: enhancement

#4033 Remove upper bound of setuptools
  pyproject.toml
Labels: enhancement

#4027 Add html module description to ui.html documentation
  website/documentation/content/html_documentation.py
Labels: documentation

#4041 Documentation: fix inverted validation rule
  nicegui/elements/number.py
Labels: documentation

#4012 JSON editor JSONSchema validation
  nicegui/elements/json_editor.js
  nicegui/elements/json_editor.py
  tests/test_json_editor.py
  website/documentation/content/json_editor_documentation.py
Labels: enhancement

#4052 update pre-commit and ruff
  .pre-commit-config.yaml
  examples/local_file_picker/local_file_picker.py
  nicegui/__init__.py
  nicegui/json/__init__.py
  nicegui/native/__init__.py
  nicegui/ui.py
  poetry.lock
  pyproject.toml
  website/documentation/__init__.py
Labels: dependencies
