Repository zauberzeug/nicegui, pull requests merged in 2024-04, with the labels that each got.

#2594 Add clipboard functions
  nicegui/functions/clipboard.py
  nicegui/ui.py
  tests/test_clipboard.py
  website/documentation/content/clipboard_documentation.py
  website/documentation/content/section_action_events.py
Labels: enhancement

#2818 More robust On Air reconnect
  nicegui/air.py
Labels: enhancement

#2809 Make libsass optional
  examples/chat_app/main.py
  examples/chat_with_ai/main.py
  nicegui/functions/style.py
  nicegui/optional_features.py
  nicegui/ui.py
  poetry.lock
  pyproject.toml
  tests/test_add_html.py
  tests/test_clipboard.py
  website/documentation/content/add_style_documentation.py
  website/documentation/content/section_styling_appearance.py
  website/documentation/rendering.py
  website/star.py
Labels: enhancement

#2803 Update Markdown elements even if invisible (e.g. inside tooltip or tab)
  nicegui/elements/markdown.js
  nicegui/elements/markdown.py
  nicegui/elements/restructured_text.py
Labels: bug

#2827 Replace check_interval for JavaScript requests with asyncio event
  nicegui/client.py
  nicegui/element.py
  nicegui/elements/aggrid.py
  nicegui/elements/echart.py
  nicegui/elements/json_editor.py
  nicegui/elements/leaflet.py
  nicegui/elements/leaflet_layer.py
  nicegui/functions/javascript.py
  nicegui/javascript_request.py
Labels: enhancement

#2836 Add method for maximizing native application
  nicegui/native/native.py
Labels: enhancement

#2837 Provide app.storage.tab
  nicegui/client.py
  nicegui/nicegui.py
  nicegui/observables.py
  nicegui/static/nicegui.js
  nicegui/storage.py
  tests/test_storage.py
  website/documentation/content/button_documentation.py
  website/documentation/content/storage_documentation.py
Labels: enhancement

#2832 Add demos for floating action buttons (fab)
  website/documentation/content/button_documentation.py
Labels: documentation

#2820 Provide app.storage.client as a location to store volatile data which only matters for the current connection
  nicegui/client.py
  nicegui/storage.py
  tests/test_storage.py
  website/documentation/content/storage_documentation.py
  website/documentation/rendering.py
Labels: enhancement

#2859 Automatically await async results in `ui.timer`
  nicegui/elements/timer.py
  tests/test_timer.py
Labels: enhancement

#2861 audio recording example
  examples/audio_recorder/audio_recorder.py
  examples/audio_recorder/audio_recorder.vue
  examples/audio_recorder/main.py
  website/examples.py
Labels: documentation

#2553 Improve interaction with Matplotlib
  nicegui/elements/pyplot.py
  nicegui/ui.py
  website/documentation/content/matplotlib_documentation.py
  website/documentation/content/section_data_elements.py
Labels: enhancement

#2855 refactor list and menu items
  nicegui/elements/context_menu.py
  nicegui/elements/item.py
  nicegui/elements/list.py
  nicegui/elements/menu.py
  nicegui/ui.py
  tests/test_button_dropdown.py
  tests/test_button_group.py
  tests/test_context_menu.py
  tests/test_list.py
  website/documentation/content/button_dropdown_documentation.py
  website/documentation/content/button_group_documentation.py
  website/documentation/content/context_menu_documentation.py
  website/documentation/content/list_documentation.py
  website/documentation/content/menu_documentation.py
Labels: enhancement

#2890 Introduce orthographic camera for `ui.scene`
  nicegui/elements/scene.js
  nicegui/elements/scene.py
  website/documentation/content/scene_documentation.py
Labels: enhancement

#2902 Fix `app.storage.tab` for NiceGUI On Air
  nicegui/air.py
Labels: bug

#2867 Replace repeated polling in Outbox.loop() with an asyncio event (see #2482)
  nicegui/outbox.py
  tests/test_input.py
  tests/test_javascript.py
Labels: bug

#2908 Fix typo in a url to FastAPI docs.
  website/documentation/content/page_documentation.py
Labels: documentation

#2922 Add early exit when setting the value of `ui.state` variables
  nicegui/functions/refreshable.py
Labels: enhancement

#2927 Show scroll to bottom in ui.table demo
  website/documentation/content/table_documentation.py
Labels: documentation

#2879 Introduce ui.context as a simpler method to get Client, Slot-Stack etc
  examples/chat_app/main.py
  examples/descope_auth/user.py
  examples/download_text_as_file/main.py
  examples/infinite_scroll/main.py
  nicegui/ui.py
  tests/test_auto_context.py
  tests/test_interactive_image.py
  tests/test_javascript.py
  tests/test_lifecycle.py
  tests/test_page.py
  tests/test_storage.py
  website/documentation/content/page_documentation.py
  website/documentation/content/storage_documentation.py
Labels: enhancement

#2905 UI context properties
  examples/chat_app/main.py
  examples/descope_auth/user.py
  examples/download_text_as_file/main.py
  examples/infinite_scroll/main.py
  nicegui/__init__.py
  nicegui/context.py
  nicegui/element.py
  nicegui/elements/carousel.py
  nicegui/elements/notification.py
  nicegui/elements/query.py
  nicegui/elements/stepper.py
  nicegui/elements/tabs.py
  nicegui/functions/download.py
  nicegui/functions/html.py
  nicegui/functions/javascript.py
  nicegui/functions/navigate.py
  nicegui/functions/notify.py
  nicegui/functions/on.py
  nicegui/functions/page_title.py
  nicegui/page_layout.py
  nicegui/storage.py
  nicegui/ui.py
  tests/test_auto_context.py
  tests/test_interactive_image.py
  tests/test_javascript.py
  tests/test_lifecycle.py
  tests/test_page.py
  tests/test_storage.py
  website/documentation/content/generic_events_documentation.py
  website/documentation/content/page_documentation.py
  website/documentation/content/query_documentation.py
  website/documentation/content/storage_documentation.py
  website/main_page.py
  website/style.py
Labels: enhancement

#2932 Initialization animation failure in ECharts
  nicegui/elements/echart.js
Labels: bug

#2884 fixed ui.download not working in native mode
  nicegui/native/native_config.py
  nicegui/native/native_mode.py
  website/documentation/content/section_configuration_deployment.py
Labels: bug

#2897 Introduce camera parameters for `ui.scene`
  nicegui/elements/scene.js
  nicegui/elements/scene.py
  website/documentation/content/scene_documentation.py
Labels: enhancement

#2944 Add class-demo to modularization example and improved structure
  examples/modularization/api_router_example.py
  examples/modularization/class_example.py
  examples/modularization/example_c.py
  examples/modularization/example_pages.py
  examples/modularization/function_example.py
  examples/modularization/home_page.py
  examples/modularization/main.py
  examples/modularization/theme.py
  nicegui/page.py
  website/documentation/content/section_action_events.py
  website/documentation/content/section_configuration_deployment.py
Labels: documentation

#2941 Example: Add zeromq example
  examples/zeromq/README.md
  examples/zeromq/images/plot.png
  examples/zeromq/main.py
  examples/zeromq/requirements.txt
  examples/zeromq/zmq-server.py
  website/examples.py
Labels: enhancement

#2789 #2549 feat: added build package script
  nicegui/scripts/pack.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#2957 Try to fix Plotly layout issues
  nicegui/elements/plotly.vue
  nicegui/static/nicegui.js
Labels: bug

#2963 Add 'clear_color' attribute to ui.scene
  nicegui/elements/scene.js
  nicegui/elements/scene.py
  website/documentation/content/scene_documentation.py
Labels: enhancement
