Repository zauberzeug/nicegui, pull requests merged in 2024-12, with the labels that each got.

#4051 update Github Action to cache docker to different locations for each platform
  .github/workflows/publish.yml
Labels: github_actions, docker

#4072 Fix upload multi-platform image by uploading separately
  .github/workflows/publish.yml
Labels: github_actions, docker

#4098 Disallow typing to disabled UI elements in `UserInteraction.type`
  nicegui/testing/user_interaction.py
  tests/test_user_simulation.py
Labels: enhancement

#4121 Prevent `ui.leaflet` from oscillating between two locations
  nicegui/elements/leaflet.js
  nicegui/elements/leaflet.py
Labels: bug

#4123 Introduce `getHtmlElement` function
  nicegui/elements/code.py
  nicegui/functions/javascript.py
  nicegui/page_layout.py
  nicegui/static/nicegui.js
  website/documentation/content/run_javascript_documentation.py
Labels: enhancement

#3199 Add message history and retransmission
  nicegui/air.py
  nicegui/app/app_config.py
  nicegui/client.py
  nicegui/nicegui.py
  nicegui/outbox.py
  nicegui/page.py
  nicegui/static/nicegui.js
  nicegui/testing/general_fixtures.py
  nicegui/ui_run.py
  nicegui/ui_run_with.py
Labels: enhancement

#4126 Only create subheading if we have class docs
  website/documentation/reference.py
Labels: documentation

#4148 Typo bugfix in elements/editor.js
  nicegui/elements/editor.js
Labels: bug
