Repository zauberzeug/nicegui, pull requests merged in 2024-08, with the labels that each got.

#3411 pytest configuration & fixtures
  examples/authentication/test_authentication.py
  examples/chat_app/test_chat_app.py
  examples/pytests/app/__init__.py
  examples/pytests/app/startup.py
  examples/pytests/main.py
  examples/pytests/pytest.ini
  examples/pytests/requirements.txt
  examples/pytests/tests/conftest.py
  examples/pytests/tests/test_with_auto_index_page.py
  examples/pytests/tests/test_with_screen.py
  examples/pytests/tests/test_with_user.py
  examples/todo_list/test_todo_list.py
  nicegui/testing/plugin.py
  pyproject.toml
  test_startup.sh
  tests/conftest.py
  tests/test_download.py
Labels: enhancement

#3424 docs: say browser session cookie is "signed", not "encrypted"
  website/documentation/content/storage_documentation.py
Labels: documentation

#3413 Add documentation of pytest fixtures and pytest configuration
  nicegui/testing/__init__.py
  nicegui/testing/plugin.py
  nicegui/testing/user.py
  tests/test_storage.py
  website/documentation/content/doc/__init__.py
  website/documentation/content/doc/api.py
  website/documentation/content/doc/part.py
  website/documentation/content/element_filter_documentation.py
  website/documentation/content/overview.py
  website/documentation/content/project_structure_documentation.py
  website/documentation/content/screen_documentation.py
  website/documentation/content/section_testing.py
  website/documentation/content/user_documentation.py
  website/documentation/search.py
Labels: documentation

#3434 Add more links to the documentation
  website/documentation/content/project_structure_documentation.py
  website/main_page.py
Labels: documentation

#2234 Provide tests for run.io_bound and run.cpu_bound
  nicegui/run.py
  tests/test_run.py
Labels: enhancement

#3439 Remove icecream dependency
  examples/pytests/requirements.txt
  nicegui/testing/plugin.py
  poetry.lock
  pyproject.toml
  tests/requirements.txt
Labels: enhancement

#3446 Reserve bottom space for error message
  nicegui/elements/mixins/validation_element.py
Labels: bug

#3444 Fix Quasar's layout rules for `ui.card` that remove children's borders and shadows
  nicegui/elements/card.py
  nicegui/static/nicegui.js
  tests/test_card.py
  website/documentation/content/card_documentation.py
Labels: enhancement

#3457 Fix JavaScript error caused by new `ui.notify`
  nicegui/functions/notify.py
  nicegui/static/nicegui.js
  nicegui/testing/plugin.py
  nicegui/testing/user.py
  nicegui/testing/user_notify.py
Labels: bug

#3466 Allow subscribing to the "drag" event for `ui.scene`
  nicegui/elements/scene.js
  website/documentation/content/scene_documentation.py
Labels: enhancement

#3463 Allow specifying the list of click events for `ui.scene`
  nicegui/elements/scene.js
  nicegui/elements/scene.py
  website/documentation/content/scene_documentation.py
Labels: documentation, enhancement

#3465 Add `get_camera` method to `ui.scene`
  nicegui/elements/scene.js
  nicegui/elements/scene.py
  website/documentation/content/scene_documentation.py
Labels: enhancement

#3476 ui.tree select/deselect, tick/untick programmatically
  nicegui/elements/tree.py
  tests/test_tree.py
  website/documentation/content/tree_documentation.py
Labels: enhancement

#3468 Add function to update a point cloud
  nicegui/elements/scene.js
  nicegui/elements/scene_objects.py
  website/documentation/content/scene_documentation.py
Labels: enhancement

#2991 Unify declaration of third-party dependencies
  examples/node_module_integration/.gitignore
  examples/node_module_integration/README.md
  examples/node_module_integration/main.py
  examples/node_module_integration/number_checker.js
  examples/node_module_integration/number_checker.py
  examples/node_module_integration/package.json
  examples/node_module_integration/webpack.config.js
  examples/signature_pad/.gitignore
  examples/signature_pad/README.md
  examples/signature_pad/main.py
  examples/signature_pad/package.json
  examples/signature_pad/signature_pad.js
  examples/signature_pad/signature_pad.py
  nicegui/element.py
  nicegui/elements/aggrid.js
  nicegui/elements/aggrid.py
  nicegui/elements/echart.js
  nicegui/elements/echart.py
  nicegui/elements/joystick.py
  nicegui/elements/joystick.vue
  nicegui/elements/json_editor.py
  nicegui/elements/mermaid.py
  nicegui/elements/plotly.py
  nicegui/elements/plotly.vue
  nicegui/elements/scene.js
  nicegui/elements/scene.py
  nicegui/elements/scene_view.py
  website/documentation/content/section_configuration_deployment.py
  website/examples.py
Labels: enhancement

#3482 Allow filtering nodes in `ui.tree`
  nicegui/elements/tree.py
  tests/test_tree.py
  website/documentation/content/tree_documentation.py
Labels: enhancement

#3453 Add support for dependabot
  .github/dependabot.yml
  fly.dockerfile
  release.dockerfile
Labels: enhancement

#3512 Add documentation for `create_user` fixture
  website/documentation/content/user_documentation.py
Labels: documentation

#3517 Add page functions to demos awaiting JavaScript from client
  nicegui/functions/javascript.py
  website/documentation/content/aggrid_documentation.py
  website/documentation/content/echart_documentation.py
  website/documentation/content/json_editor_documentation.py
  website/documentation/content/run_javascript_documentation.py
Labels: documentation

#3511 Provide two additional pytest plugins to make user and screen able to load independently
  examples/authentication/test_authentication.py
  examples/chat_app/test_chat_app.py
  examples/todo_list/test_todo_list.py
  nicegui/testing/general_fixtures.py
  nicegui/testing/plugin.py
  nicegui/testing/screen_plugin.py
  nicegui/testing/user_plugin.py
  tests/test_download.py
  website/documentation/content/project_structure_documentation.py
  website/documentation/content/user_documentation.py
Labels: enhancement

#3452 Move "is_initialized" flag for 3D scene from server to client
  nicegui/elements/scene.js
  nicegui/elements/scene.py
  nicegui/elements/scene_view.py
Labels: bug

#3524 Fix events on hidden and disabled elements
  nicegui/client.py
  nicegui/events.py
  tests/test_events.py
Labels: bug

#3548 Avoid importing pandas if not needed
  nicegui/elements/aggrid.py
  nicegui/elements/table.py
Labels: enhancement

#3525 Improve the API of `ui.table`
  examples/table_and_slots/main.py
  nicegui/elements/table.py
  tests/test_table.py
  website/documentation/content/table_documentation.py
Labels: enhancement

#3553 Add link to example with plugins for full calendar
  examples/fullcalendar/fullcalendar.py
Labels: documentation

#3559 Lazy-load NumPy only if it is needed
  nicegui/json/builtin_wrapper.py
  nicegui/json/orjson_wrapper.py
Labels: enhancement

#3561 Fix bug when opening/closing `ui.select` on air
  nicegui/air.py
Labels: bug

#3580 Delay events before handshake
  nicegui/static/nicegui.js
Labels: bug

#3579 Support creating background tasks from awaitables
  nicegui/background_tasks.py
Labels: bug

#3587 Use correct version for citation file
  .github/workflows/publish.yml
  .github/workflows/update_citation.py
Labels: enhancement

#3595 Use newer langchain package
  examples/chat_with_ai/requirements.txt
Labels: enhancement

#3585 Allow nicegui.test to be used without selenium dependencies
  nicegui/testing/__init__.py
Labels: bug

#3589 Disable FastAPI docs by default
  nicegui/app/app.py
  nicegui/ui_run.py
  tests/test_endpoint_docs.py
Labels: enhancement

#3600 Introduce `IconElement` mixin
  nicegui/elements/avatar.py
  nicegui/elements/button.py
  nicegui/elements/button_dropdown.py
  nicegui/elements/chip.py
  nicegui/elements/expansion.py
  nicegui/elements/mixins/icon_element.py
  nicegui/elements/stepper.py
  nicegui/elements/tabs.py
  nicegui/elements/teleport.py
  nicegui/elements/timeline.py
Labels: enhancement

#3619 Ensure cv2.VideoCapture is only called once
  examples/opencv_webcam/main.py
Labels: bug

#3586 Improve support for drawing items in `ui.leaflet`
  nicegui/elements/leaflet.js
  nicegui/elements/leaflet.py
  nicegui/static/utils/json.js
  website/documentation/content/leaflet_documentation.py
Labels: enhancement

#3582 feat: implement access method for get_client_data
  nicegui/elements/aggrid.py
  tests/test_aggrid.py
Labels: enhancement

#3623 Remove upper bound for FastAPI version
  poetry.lock
  pyproject.toml
Labels: dependencies

#3588 Provide public API for accessing `_props`, `_classes` and `_style`.
  nicegui/classes.py
  nicegui/element.py
  nicegui/element_filter.py
  nicegui/elements/carousel.py
  nicegui/elements/menu.py
  nicegui/elements/mixins/visibility.py
  nicegui/elements/query.py
  nicegui/elements/stepper.py
  nicegui/elements/tabs.py
  nicegui/elements/tree.py
  nicegui/page_layout.py
  nicegui/props.py
  nicegui/style.py
  nicegui/testing/user_interaction.py
  tests/test_element.py
  tests/test_element_filter.py
  tests/test_tailwind.py
  tests/test_tree.py
  website/documentation/content/mermaid_documentation.py
  website/documentation/content/section_styling_appearance.py
Labels: enhancement

#3648 Remove and update deprecated APIs
  nicegui/client.py
  nicegui/context.py
  nicegui/element.py
  nicegui/elements/aggrid.py
  nicegui/elements/chart.py
  nicegui/elements/echart.py
  nicegui/elements/json_editor.py
  nicegui/elements/leaflet.py
  nicegui/elements/leaflet_layer.py
  nicegui/elements/table.py
  nicegui/functions/javascript.py
  nicegui/functions/open.py
  nicegui/functions/style.py
  nicegui/page_layout.py
  nicegui/storage.py
  nicegui/testing/conftest.py
  nicegui/ui.py
Labels: enhancement

#3647 Remove ui.timer objects from hierarchy
  nicegui/client.py
  nicegui/elements/timer.py
  tests/test_timer.py
Labels: bug

#3660 Hide bottom space for error message when validation is `None`
  nicegui/elements/input.py
  nicegui/elements/mixins/validation_element.py
  nicegui/elements/number.py
  nicegui/elements/select.py
  nicegui/elements/textarea.py
Labels: enhancement
