Repository zauberzeug/nicegui, pull requests merged in 2024-01, with the labels that each got.

#2250 Allow http range requests with On Air (eg. serving media files)
  nicegui/air.py
  nicegui/app/app.py
  nicegui/app/range_response.py
  nicegui/app/streaming_response.py
  nicegui/nicegui.py
  nicegui/templates/index.html
Labels: enhancement

#2281 Additional ui.expansion options
  nicegui/elements/expansion.py
  tests/test_expansion.py
  website/documentation/content/expansion_documentation.py
Labels: enhancement

#2272 Keep updates and messages in outbox until client is connected
  nicegui/air.py
  nicegui/client.py
  nicegui/core.py
  nicegui/element.py
  nicegui/functions/javascript.py
  nicegui/functions/notify.py
  nicegui/nicegui.py
  nicegui/outbox.py
  nicegui/testing/conftest.py
  nicegui/ui_run.py
  tests/test_element.py
  tests/test_javascript.py
  tests/test_outbox.py
  tests/test_refreshable.py
Labels: bug

#2268 Introduce `ui.refreshable_method`
  nicegui/functions/refreshable.py
  nicegui/ui.py
  tests/test_refreshable.py
Labels: bug

#2288 Dynamically hide `ui.code`'s copy button
  nicegui/elements/code.py
Labels: enhancement

#2306 improve documentation about async/await
  website/documentation/content/overview.py
Labels: documentation

#2305 Put .local/bin in PATH so pip installed programs like pytest are executable
  docker-entrypoint.sh
Labels: enhancement

#2322 Fix a problem with Storage not working in python 3.8
  nicegui/storage.py
Labels: bug

#2311 Optimize binding propagation
  nicegui/binding.py
Labels: enhancement

#2320 Introduce pyserial example
  examples/pyserial/main.py
  examples/pyserial/requirements.txt
  test_startup.sh
  website/examples.py
Labels: documentation

#2323 Improve binding documentation
  nicegui/binding.py
  nicegui/elements/mixins/content_element.py
  nicegui/elements/mixins/disableable_element.py
  nicegui/elements/mixins/filter_element.py
  nicegui/elements/mixins/name_element.py
  nicegui/elements/mixins/source_element.py
  nicegui/elements/mixins/text_element.py
  nicegui/elements/mixins/value_element.py
  nicegui/elements/mixins/visibility.py
  website/documentation/content/section_binding_properties.py
Labels: documentation

#2342 Fix updating of error message for validation elements
  nicegui/elements/input.py
  nicegui/elements/mixins/validation_element.py
  nicegui/elements/number.py
  nicegui/elements/textarea.py
  tests/test_input.py
Labels: bug

#2360 Update dependencies and socketio path behavior
  examples/opencv_webcam/main.py
  nicegui/nicegui.py
  poetry.lock
  pyproject.toml
Labels: bug

#2363 add explanation for run.cpu_bound
  nicegui/run.py
Labels: documentation

#2376 Allow calling `ui.open` without a socket connection
  nicegui/functions/open.py
Labels: enhancement

#2374 Improve performance for removing bindings
  nicegui/binding.py
Labels: enhancement

#2380 Ability to dismiss notifications
  nicegui/elements/notification.js
  nicegui/elements/notification.py
  tests/test_notification.py
  website/documentation/content/notification_documentation.py
Labels: enhancement

#2396 Allow handling Mermaid errors on the server
  nicegui/elements/mermaid.js
  tests/test_mermaid.py
  website/documentation/content/mermaid_documentation.py
Labels: enhancement

#2399 provide client.request and make client.ip available even before client.connected (breaking change)
  nicegui/client.py
  nicegui/nicegui.py
  nicegui/page.py
  nicegui/testing/conftest.py
  tests/test_page.py
Labels: enhancement

#2403 Introduce from_pyecharts method for ui.echart
  fly.dockerfile
  nicegui/elements/echart.py
  nicegui/optional_features.py
  poetry.lock
  pyproject.toml
  tests/test_echart.py
  website/documentation/content/echart_documentation.py
Labels: enhancement

#2412 provide meta data for wrapped page-builder
  nicegui/page.py
Labels: enhancement

#2413 Add support for calling AG Grid row methods
  nicegui/elements/aggrid.js
  nicegui/elements/aggrid.py
  tests/test_aggrid.py
  website/documentation/content/aggrid_documentation.py
Labels: enhancement

#2418 Introduce layer methods for Leaflet elements
  nicegui/elements/leaflet.js
  nicegui/elements/leaflet.py
  nicegui/elements/leaflet_layer.py
  nicegui/elements/leaflet_layers.py
  website/documentation/content/leaflet_documentation.py
Labels: enhancement

#2434 Add support for Material Symbols
  fetch_google_fonts.py
  nicegui/static/fonts.css
  nicegui/static/fonts/LDItaoyNOAY6Uewc665JcIzCKsKc_M9flwmPq_HTTw.woff2
  nicegui/static/fonts/gNNBW2J8Roq16WD5tFNRaeLQk6-SHQ_R00k4c2_whPnoY9ruReaU4bHmz74m0ZkGH-VBYe1x0TV6x4yFH8F-H5OdzEL3sVTgJtfbYxOLojCLJ1H7-0Hk.woff2
  nicegui/static/fonts/gok-H7zzDkdnRel8-DQ6KAXJ69wP1tGnf4ZGhUcel5euIg.woff2
  nicegui/static/fonts/kJF1BvYX7BgnkSrUwT8OhrdQw4oELdPIeeII9v6oDMzByHX9rA6RzaxHMPdY43zj-jCxv3fzvRNU22ZXGJpEpjC_1v-p_4MrImHCIJIZrDCvHOejbd5zrDAt.woff2
  nicegui/static/fonts/oPWQ_lt5nv4pWNJpghLP75WiFR4kLh3kvmvRImcycg.woff2
  nicegui/static/fonts/syl0-zNym6YjUruM-QrEh7-nyTnjDwKNJ_190FjpZIvDmUSVOK7BDB_Qb9vUSzq3wzLK-P0J-V_Zs-QtQth3-jOcbTCVpeRL2w5rwZu2rIelXxeJKJBiCa8.woff2
  website/documentation/content/icon_documentation.py
Labels: enhancement

#2426 require asyncio-client which installs aiohttp dependency
  poetry.lock
  pyproject.toml
Labels: bug

#2432 Add example on how to use websockets library
  examples/websockets/main.py
  examples/websockets/requirements.txt
  website/examples.py
Labels: documentation

#2447 make log.js autoscroll to bottom when page is loaded
  nicegui/elements/log.js
Labels: enhancement

#2450 serve fuse.js from our domain not CDN
  website/static/fuse.js@7.0.0
  website/static/header.html
Labels: enhancement

#2445 Better error message when storage_secret is missing
  examples/authentication/main.py
  nicegui/storage.py
Labels: bug

#2449 Let ui.audio and ui.video inherit from SourceElement
  nicegui/elements/audio.py
  nicegui/elements/mixins/source_element.py
  nicegui/elements/video.py
  tests/test_audio.py
  tests/test_video.py
Labels: enhancement

#2452 Update list of features
  website/main_page.py
Labels: documentation

#2453 Add loaded event which fires when source of ui.interactive_image changes
  nicegui/elements/interactive_image.js
  tests/test_interactive_image.py
  website/documentation/content/interactive_image_documentation.py
Labels: enhancement

#2451 Only update tailwind.config.darkMode if value has changed
  nicegui/elements/dark_mode.js
Labels: bug

#2459 fix broken target links in documentation strings
  nicegui/api_router.py
  nicegui/functions/open.py
  nicegui/page.py
  nicegui/ui_run.py
Labels: documentation
