Repository zauberzeug/nicegui, pull requests merged in 2024-06, with the labels that each got.

#3162 Inaccurate error message in `ui.image` when file does not exist
  nicegui/elements/mixins/source_element.py
Labels: enhancement

#3159 Introduce `ui.teleport` element
  nicegui/elements/teleport.js
  nicegui/elements/teleport.py
  nicegui/testing/screen.py
  nicegui/ui.py
  tests/test_teleport.py
  website/documentation/content/section_page_layout.py
  website/documentation/content/teleport_documentation.py
Labels: enhancement

#3164 Add optional config dictionary to mermaid component to be passed initialize() on mount
  nicegui/elements/mermaid.js
  nicegui/elements/mermaid.py
  tests/test_mermaid.py
  website/documentation/content/mermaid_documentation.py
Labels: enhancement

#3175 Introduce `align_items` parameter for `ui.row`, `ui.column` and `ui.card`
  nicegui/elements/card.py
  nicegui/elements/column.py
  nicegui/elements/row.py
Labels: enhancement

#3186 Fixed npm import script.
  npm.py
Labels: bug

#3214 Fix link to Quasar's time component in docs
  nicegui/elements/time.py
Labels: documentation

#3230 Use ui.teleport to create fancy radio options
  website/documentation/content/radio_documentation.py
  website/documentation/content/teleport_documentation.py
Labels: documentation

#3195 Added support for 3D graphing for echarts.
  DEPENDENCIES.md
  nicegui/elements/echart.py
  nicegui/elements/lib/echarts-gl/echarts-gl.js.map
  nicegui/elements/lib/echarts-gl/echarts-gl.min.js
  npm.json
  npm.py
  website/documentation/content/echart_documentation.py
Labels: enhancement

#3202 Add skeleton element
  nicegui/elements/skeleton.py
  nicegui/ui.py
  website/documentation/content/section_page_layout.py
  website/documentation/content/skeleton_documentation.py
Labels: enhancement

#3226 Improve date picker demo with input element and add similar demo for time picker
  website/documentation/content/date_documentation.py
  website/documentation/content/time_documentation.py
Labels: documentation

#3235 Extend ui.upload documentation with an example for large file uploads.
  website/documentation/content/upload_documentation.py
Labels: documentation

#3213 Add details and examples in docs for running apps with https
  examples/nginx_https/README.md
  examples/nginx_https/app/main.py
  examples/nginx_https/docker-compose.yml
  examples/nginx_https/nginx.conf
  examples/nginx_https/nginx_site.conf
  website/documentation/content/section_configuration_deployment.py
Labels: documentation

#3281 ui.number value discrepancy
  nicegui/elements/number.py
  tests/test_number.py
Labels: bug

#3286 Add request object to the client
  nicegui/client.py
  nicegui/nicegui.py
  nicegui/page.py
  nicegui/testing/conftest.py
  website/documentation/content/section_configuration_deployment.py
Labels: enhancement

#3260 Add min, max and step properties for `ui.range`
  nicegui/elements/range.py
  website/documentation/content/range_documentation.py
Labels: enhancement

#3257 Allow changing grid parameters of `ui.scene`
  nicegui/elements/scene.js
  nicegui/elements/scene.py
  website/documentation/content/scene_documentation.py
Labels: enhancement

#3279 Add demos for using `ui.refreshable` with local scope
  website/documentation/content/refreshable_documentation.py
Labels: documentation

#3289 Let SVG of `ui.pyplot` fill its container
  nicegui/elements/pyplot.py
  nicegui/static/nicegui.css
Labels: bug

#3296 Ignore `CancelledError` in `check_for_late_return_value`
  nicegui/page.py
  nicegui/run.py
Labels: bug

#3305 Provide info on how to run the docs locally
  README.md
Labels: documentation
