Repository zauberzeug/nicegui, pull requests merged in 2025-07, with the labels that each got.

#4822 Perf: Crackdown on style recals
  website/documentation/demo.py
  website/star.py
  website/static/loading.gif
Labels: documentation, review, ⚪️ minor

#4919 Use code.js component to avoid memory-leaky on_connect registration
  nicegui/elements/code.js
  nicegui/elements/code.py
Labels: bug, review, 🟠 major

#4916 Avoid duplicate values in `ui.select` in "add-unique" mode
  nicegui/elements/select.py
  tests/test_select.py
Labels: bug, review

#4937 Let `ui.header` update `scrollPaddingTop` more nicely with a custom header.js component
  nicegui/elements/drawer.py
  nicegui/elements/footer.py
  nicegui/elements/header.js
  nicegui/elements/header.py
  nicegui/elements/page_sticky.py
  nicegui/helpers.py
  nicegui/ui.py
Labels: bug, review, ⚪️ minor

#4943 Support async nested sub pages
  examples/single_page_app/custom_sub_pages.py
  nicegui/client.py
  nicegui/elements/sub_pages.js
  nicegui/elements/sub_pages.py
  nicegui/functions/navigate.py
  nicegui/page_args.py
  nicegui/sub_pages_router.py
  tests/test_sub_pages.py
  website/documentation/content/sub_pages_documentation.py
Labels: feature, in progress, 🌳 advanced

#4906 Make ui.sub_pages navigation aware of url fragments
  examples/single_page_app/custom_sub_pages.py
  nicegui/client.py
  nicegui/elements/sub_pages.js
  nicegui/elements/sub_pages.py
  nicegui/functions/navigate.py
  nicegui/page_args.py
  nicegui/sub_pages_router.py
  tests/test_sub_pages.py
  website/documentation/content/sub_pages_documentation.py
Labels: feature

#4905 Introduce PageArgs for ui.sub_pages for query parameters and data access
  examples/single_page_app/custom_sub_pages.py
  nicegui/__init__.py
  nicegui/client.py
  nicegui/elements/sub_pages.js
  nicegui/elements/sub_pages.py
  nicegui/functions/navigate.py
  nicegui/page_args.py
  nicegui/sub_pages_router.py
  tests/test_sub_pages.py
  website/documentation/content/sub_pages_documentation.py
Labels: feature

#4938 Remove cyclic references within clients and elements
  fetch_tailwind.py
  nicegui/classes.py
  nicegui/element.py
  nicegui/elements/pyplot.py
  nicegui/elements/query.py
  nicegui/outbox.py
  nicegui/props.py
  nicegui/slot.py
  nicegui/style.py
  nicegui/tailwind.py
  tests/test_element.py
  tests/test_scene.py
Labels: feature, review

#4813 Feat: `ui.fab` and `ui.fab_action` element
  nicegui/elements/fab.py
  nicegui/elements/menu.py
  nicegui/ui.py
  tests/test_fab.py
  website/documentation/content/button_documentation.py
  website/documentation/content/fab_documentation.py
  website/documentation/content/overview.py
  website/documentation/content/section_controls.py
Labels: feature, review, ⚪️ minor

#4955 Add None to the return type of WindowProxy.create_file_dialog
  nicegui/native/native.py
Labels: bug

#4984 Add a `ui.button_dropdown.on_click` method for registering click event handlers
  nicegui/elements/button_dropdown.py
Labels: feature, review

#4982 Reduce redis data and connections for API requests
  examples/redis_storage/docker-compose.yml
  nicegui/persistence/redis_persistent_dict.py
  nicegui/storage.py
  website/documentation/content/storage_documentation.py
Labels: bug, review
