Repository zauberzeug/nicegui, pull requests merged in 2025-06, with the labels that each got.

#4812 Fix the development container to keep working with Python 3.8
  development.dockerfile
Labels: infrastructure, review, 🟡 medium, 🌿 intermediate

#4540 Support ui.run(cache_control_directives=)
  nicegui/app/app_config.py
  nicegui/middlewares.py
  nicegui/nicegui.py
  nicegui/ui_run.py
  nicegui/ui_run_with.py
  tests/test_serving_files.py
Labels: feature, review, 🟡 medium

#4632 Pin version for JS dependencies
  .dockerignore
  .gitignore
  .syncignore
  .vscode/settings.json
  CONTRIBUTING.md
  npm.json
  package.json
  pin_version.py
Labels: infrastructure, review, 🟡 medium

#4841 Remove wait_for2 dependency
  nicegui/air.py
  nicegui/background_tasks.py
  nicegui/helpers.py
  nicegui/javascript_request.py
  nicegui/outbox.py
  poetry.lock
  pyproject.toml
Labels: feature, review

#4846 Improve coding rules and make them available in CONTRIBUTING.md
  .cursor/rules/coding.mdc
  CONTRIBUTING.md
Labels: documentation, review, 🟡 medium

#4538 Customizable error screen w/ clean traceback (even async)
  nicegui/app/app.py
  nicegui/events.py
  nicegui/helpers.py
  nicegui/page.py
  website/documentation/content/overview.py
  website/documentation/content/section_action_events.py
Labels: feature, review, 🟡 medium, 🌿 intermediate

#4893 Fix deselection of table rows by using the correct row key
  nicegui/elements/table.py
Labels: bug, review

#4910 Make binding transform functions optional
  nicegui/binding.py
  nicegui/elements/mixins/content_element.py
  nicegui/elements/mixins/disableable_element.py
  nicegui/elements/mixins/filter_element.py
  nicegui/elements/mixins/icon_element.py
  nicegui/elements/mixins/label_element.py
  nicegui/elements/mixins/name_element.py
  nicegui/elements/mixins/selectable_element.py
  nicegui/elements/mixins/source_element.py
  nicegui/elements/mixins/text_element.py
  nicegui/elements/mixins/value_element.py
  nicegui/elements/mixins/visibility.py
Labels: feature, review
