Repository zauberzeug/nicegui, pull requests merged in 2025-01, with the labels that each got.

#4153 Demonstrate dialog event registration
  website/documentation/content/dialog_documentation.py
Labels: documentation

#4136 Add example to show OpenAI's Assistant API with async/await
  examples/chat_with_ai/main.py
  examples/openai_assistant/main.py
  examples/openai_assistant/requirements.txt
  website/examples.py
Labels: documentation

#4144 add `read_image` api to `ui.clipboard`
  nicegui/functions/clipboard.py
  website/documentation/content/clipboard_documentation.py
Labels: enhancement

#4192 Fix potential matplotlib warning when using ui.line_plot.push
  nicegui/elements/line_plot.py
  website/documentation/content/line_plot_documentation.py
Labels: enhancement

#4128 Introduce a "Map of NiceGUI"
  nicegui/ui_run.py
  website/documentation/content/overview.py
Labels: documentation

#4221 Add version information to documentation
  nicegui/app/app.py
  nicegui/classes.py
  nicegui/client.py
  nicegui/element.py
  nicegui/elements/aggrid.py
  nicegui/elements/card.py
  nicegui/elements/colors.py
  nicegui/elements/echart.py
  nicegui/elements/json_editor.py
  nicegui/elements/leaflet.py
  nicegui/elements/mixins/validation_element.py
  nicegui/elements/query.py
  nicegui/elements/scene_object3d.py
  nicegui/elements/table.py
  nicegui/functions/javascript.py
  nicegui/functions/navigate.py
  nicegui/functions/style.py
  nicegui/page_layout.py
  nicegui/timer.py
  nicegui/ui_run.py
  nicegui/ui_run_with.py
  website/documentation/content/aggrid_documentation.py
  website/documentation/content/colors_documentation.py
  website/documentation/content/html_documentation.py
  website/documentation/content/input_documentation.py
  website/documentation/content/interactive_image_documentation.py
  website/documentation/content/json_editor_documentation.py
  website/documentation/content/page_documentation.py
  website/documentation/content/scene_documentation.py
  website/documentation/content/section_text_elements.py
  website/documentation/content/storage_documentation.py
  website/documentation/content/table_documentation.py
  website/documentation/content/timer_documentation.py
  website/documentation/content/user_documentation.py
Labels: documentation

#4232 dynamically mirror 'Other HTML elements' demo
  website/documentation/content/html_documentation.py
  website/documentation/content/section_text_elements.py
Labels: documentation

#4235 Bulk vue updates on update
  nicegui/static/nicegui.js
Labels: enhancement

#3987 Introduce bindable dataclass fields
  nicegui/__init__.py
  nicegui/binding.py
  tests/test_binding.py
  website/documentation/content/overview.py
  website/documentation/content/section_binding_properties.py
Labels: enhancement

#4265 Prevent leaflet from resetting center and zoom when browser resizes
  nicegui/elements/leaflet.js
  nicegui/elements/leaflet.py
Labels: bug

#4272 Do not replace main page with an empty one
  website/documentation/content/storage_documentation.py
Labels: bug

#4229 A couple of small improvements to the custom vue component example
  examples/custom_vue_component/README.md
  examples/custom_vue_component/counter.js
  examples/custom_vue_component/main.py
  examples/custom_vue_component/on_off.py
  examples/custom_vue_component/on_off.vue
Labels: documentation

#4289 Enable usage of leaflet plugins (#2767)
  nicegui/elements/leaflet.js
  nicegui/elements/leaflet.py
  website/documentation/content/leaflet_documentation.py
Labels: enhancement
