Repository zauberzeug/nicegui, pull requests merged in 2025-08, with the labels that each got.

#4999 Fix: only use SPA router for relative URLs in ui.navigate.to
  nicegui/functions/navigate.py
  tests/test_navigate.py
Labels: in progress, 🔴 critical

#5015 Switch to Jsdelivr CDN for downloading NPM packages
  npm.json
  npm.py
Labels: infrastructure

#5019 Don't require plotly being installed for using `ui.plotly`'s dictionary interface
  nicegui/elements/plotly.py
Labels: bug, review, 🟡 medium

#5025 Fix bad navigation of relative urls
  nicegui/functions/navigate.py
  tests/test_navigate.py
Labels: bug, review, 🔴 critical

#4456 Introduce `ValueChangeEventArguments.previous_value`
  nicegui/elements/mixins/selectable_element.py
  nicegui/elements/mixins/value_element.py
  nicegui/elements/table.py
  nicegui/elements/tree.py
  nicegui/events.py
  tests/test_events.py
Labels: feature, review, ⚪️ minor

#5039 Add Stripe checkout example with FastAPI integration
  examples/stripe/main.py
  examples/stripe/requirements.txt
  website/examples.py
Labels: documentation, review

#5042 Fix Tailwind for `ui.dark_mode` in combination with `ui.run(dark=None)`
  nicegui/elements/dark_mode.js
  nicegui/elements/dark_mode.py
  nicegui/templates/index.html
  tests/test_dark_mode.py
Labels: bug, review, 🟠 major

#5050 Fix jumpy dialog
  main.py
  nicegui/elements/dialog.js
  nicegui/elements/dialog.py
  nicegui/elements/select.js
  nicegui/static/nicegui.css
  tests/test_dialog.py
  tests/test_select.py
  website/__init__.py
  website/anti_scroll_hack.py
  website/static/style.css
Labels: bug, review, 🟡 medium

#5053 Use weak references for parent slot to avoid cyclic references
  nicegui/element.py
  nicegui/elements/timer.py
  tests/test_element.py
Labels: bug, review

#5063 Allow combination of x-forwarded-prefix and root_path
  nicegui/client.py
Labels: bug, review

#5064 Handle breaking change of pywebview's dialog type
  nicegui/native/native.py
Labels: bug, review

#5067 Always load ESM module shims, but async
  nicegui/templates/index.html
Labels: bug, review

#4978 Make props, classes and style observable to send updates automatically
  examples/custom_binding/main.py
  examples/fullcalendar/fullcalendar.py
  nicegui/classes.py
  nicegui/elements/aggrid/aggrid.py
  nicegui/elements/chip.py
  nicegui/elements/choice_element.py
  nicegui/elements/codemirror/codemirror.py
  nicegui/elements/colors.py
  nicegui/elements/fullscreen.py
  nicegui/elements/image.py
  nicegui/elements/input.py
  nicegui/elements/interactive_image.py
  nicegui/elements/line_plot.py
  nicegui/elements/markdown.py
  nicegui/elements/mixins/content_element.py
  nicegui/elements/mixins/disableable_element.py
  nicegui/elements/mixins/filter_element.py
  nicegui/elements/mixins/icon_element.py
  nicegui/elements/mixins/label_element.py
  nicegui/elements/mixins/name_element.py
  nicegui/elements/mixins/selectable_element.py
  nicegui/elements/mixins/source_element.py
  nicegui/elements/mixins/validation_element.py
  nicegui/elements/mixins/value_element.py
  nicegui/elements/mixins/visibility.py
  nicegui/elements/notification.py
  nicegui/elements/number.py
  nicegui/elements/pagination.py
  nicegui/elements/plotly/plotly.py
  nicegui/elements/pyplot.py
  nicegui/elements/range.py
  nicegui/elements/restructured_text.py
  nicegui/elements/table.py
  nicegui/elements/tree.py
  nicegui/props.py
  nicegui/style.py
  tests/test_aggrid.py
  tests/test_echart.py
  tests/test_element.py
  tests/test_highchart.py
  website/documentation/content/aggrid_documentation.py
  website/documentation/content/button_documentation.py
  website/documentation/content/echart_documentation.py
  website/documentation/content/highchart_documentation.py
  website/documentation/content/section_action_events.py
  website/documentation/content/section_styling_appearance.py
  website/documentation/content/table_documentation.py
  website/documentation/custom_restructured_text.py
Labels: feature, review

#5069 Implement "user.should_see" and "click" for ui.tree
  nicegui/element_filter.py
  nicegui/elements/tree.py
  nicegui/testing/user_interaction.py
  tests/test_user_simulation.py
Labels: testing, review
