Repository zauberzeug/nicegui, pull requests merged in 2025-04, with the labels that each got.

#4512 Pytest: JavaScript calls should not time out when using the user fixture
  nicegui/page_layout.py
  nicegui/testing/user.py
  nicegui/testing/user_plugin.py
  tests/test_user_simulation.py
  website/documentation/content/user_documentation.py
Labels: feature, review

#4555 Chunk large http responses when relayed through On Air service
  nicegui/air.py
Labels: feature, review, 🟠 major

#4529 refactor: Introduces `LabelElement`
  nicegui/elements/chat_message.py
  nicegui/elements/color_input.py
  nicegui/elements/input.py
  nicegui/elements/mixins/label_element.py
  nicegui/elements/number.py
  nicegui/elements/select.py
  nicegui/elements/tabs.py
  nicegui/elements/upload.py
Labels: feature, review, ⚪️ minor, 🌱 beginner

#4543 Support on_begin_upload for ui.upload
  nicegui/elements/upload.py
Labels: feature, review, ⚪️ minor, 🌿 intermediate

#4550 Avoid RuntimeError while iterating over bindable properties
  nicegui/binding.py
Labels: bug, analysis, in progress, 🌿 intermediate

#4572 Add @ui.page('/') to fix output_selected_row
  website/documentation/content/aggrid_documentation.py
Labels: documentation, review

#4582 Provide better warning if On Air service is not reachable
  nicegui/air.py
Labels: review, 🟡 medium

#4576 Fix docs section_styling_appearance label bug
  website/documentation/content/section_styling_appearance.py
Labels: documentation, review

#4564 Introduce more explicit download functions
  nicegui/functions/download.py
  nicegui/testing/user_download.py
  tests/test_download.py
  tests/test_user_simulation.py
  website/documentation/content/download_documentation.py
Labels: feature, review, ⚪️ minor, 🌱 beginner

#4595 let SVG of `ui.matplotlib` fill its container as well
  nicegui/elements/pyplot.py
  nicegui/static/nicegui.css
Labels: bug, review, 🟡 medium

#4596 Add theme support to ECharts
  nicegui/elements/echart.js
  nicegui/elements/echart.py
  tests/test_echart.py
  website/documentation/content/echart_documentation.py
Labels: feature, review

#4481 Set explicitly font-display: block to exchange "flash of unstyled text" (FOUT) for “flash of invisible text” (FOIT)?
  fetch_google_fonts.py
  nicegui/static/fonts.css
Labels: feature, review, 🟡 medium, 🌿 intermediate

#4608 Fix unexpected logs in pytest when using the user fixture
  nicegui/testing/user_plugin.py
Labels: testing, review

#4619 Use a WeakValueDictionary instead of custom finalizers
  nicegui/binding.py
Labels: bug, review, 🔴 critical

#4628 Introduce a `_propagation_context` to keep track of visited properties
  nicegui/binding.py
Labels: bug, review, 🟠 major

#4635 Use `element._update_method` for `ui.codemirror`
  nicegui/elements/codemirror.js
  nicegui/elements/codemirror.py
Labels: bug, review

#4640 docs(upload_documentation.py): update documentation on ui.upload to use new parameter name
  website/documentation/content/upload_documentation.py
Labels: documentation, review

#4633 Introduce element.html_id property
  nicegui/element.py
  nicegui/elements/link.py
  nicegui/elements/teleport.py
  nicegui/functions/navigate.py
  nicegui/testing/screen.py
  tests/test_scene.py
  website/documentation/content/radio_documentation.py
  website/documentation/content/teleport_documentation.py
Labels: feature, review, ⚪️ minor

#4646 Add demo about HTML in `ui.table` cells
  website/documentation/content/table_documentation.py
Labels: documentation, review

#4648 Use custom reST element for documentation (fixes #4647)
  website/documentation/__init__.py
  website/documentation/custom_restructured_text.py
  website/documentation/reference.py
  website/documentation/rendering.py
  website/search.py
Labels: documentation, review

#4653 Fix "leaked semaphore object" warnings
  nicegui/native/__init__.py
  nicegui/native/native.py
  nicegui/native/native_mode.py
  nicegui/nicegui.py
  nicegui/run.py
  nicegui/ui_run.py
Labels: feature, review, 🟡 medium

#4658 Added documentation on how native app settings are ignored when using a main guard
  website/documentation/content/section_configuration_deployment.py
Labels: documentation, review

#4672 Tolerant gethtmlelement
  nicegui/static/nicegui.js
Labels: feature, review

#4675 Make passing `Element` to `getElement` work
  nicegui/static/nicegui.js
Labels: bug, review

#4676 Simplify change set processing for `ui.codemirror`
  nicegui/elements/codemirror.py
  tests/test_codemirror.py
Labels: feature

#4641 Properly await coroutines registered with app.on_shutdown
  .github/workflows/update_version.py
  nicegui/air.py
  nicegui/app/app.py
  nicegui/app/range_response.py
  nicegui/background_tasks.py
  nicegui/binding.py
  nicegui/client.py
  nicegui/elements/mixins/validation_element.py
  nicegui/events.py
  nicegui/functions/refreshable.py
  nicegui/helpers.py
  nicegui/javascript_request.py
  nicegui/nicegui.py
  nicegui/outbox.py
  nicegui/persistence/file_persistent_dict.py
  nicegui/slot.py
  nicegui/storage.py
  nicegui/testing/screen_plugin.py
  nicegui/testing/user_download.py
  nicegui/testing/user_interaction.py
  nicegui/testing/user_navigate.py
  poetry.lock
  pyproject.toml
  tests/test_background_tasks.py
  tests/test_storage.py
  website/documentation/content/overview.py
  website/documentation/content/section_configuration_deployment.py
Labels: feature, testing, review, 🟠 major
