Repository zauberzeug/nicegui, pull requests merged in 2025-03, with the labels that each got.

#4401 Wait for leaflet to load before loading additional resources.
  nicegui/elements/leaflet.js
Labels: bug

#4368 Add ruff quote-style
  .vscode/settings.json
  pyproject.toml
Labels: enhancement

#4388 Pass referrer_path to /login as a query parameter
  examples/authentication/main.py
Labels: documentation

#4334 Drawer inherits ValueElement
  nicegui/page_layout.py
Labels: enhancement

#4358 Introduce QSlideItem element
  nicegui/elements/slide_item.py
  nicegui/events.py
  nicegui/ui.py
  tests/test_slide_item.py
  tests/test_user_simulation.py
  website/documentation/content/section_page_layout.py
  website/documentation/content/slide_item_documentation.py
Labels: enhancement

#4411 flag for file existence checks on add_static_file
  nicegui/app/app.py
Labels: enhancement

#4445 Introduce Cursor rules to improve quality of AI
  .cursor/rules/coding.mdc
  .cursor/rules/general.mdc
  .dockerignore
  .syncignore
Labels: enhancement

#3244 Add Google one-tap authentication example
  .gitignore
  examples/google_one_tap_auth/main.py
Labels: enhancement

#4443 Ensure valid host when opening native window
  nicegui/ui_run.py
Labels: bug

#4458 Fix native select and change event capture for `json_editor` element.
  nicegui/elements/json_editor.js
  nicegui/elements/json_editor.py
Labels: bug

#4444 feat: add `timeout` method for `ui.notification`
  nicegui/elements/notification.py
Labels: enhancement

#4371 Add Google OAuth2 example
  examples/google_oauth2/main.py
  examples/google_oauth2/requirements.txt
  website/examples.py
Labels: documentation

#4466 Introduce `_waiting_for_connection` event for more efficient page function
  nicegui/client.py
  nicegui/page.py
Labels: enhancement

#4470 Allow defining an update method as part of an element's dictionary
  nicegui/element.py
  nicegui/elements/aggrid.py
  nicegui/elements/echart.py
  nicegui/elements/json_editor.py
  nicegui/elements/notification.py
  nicegui/elements/plotly.py
  nicegui/elements/teleport.py
  nicegui/static/nicegui.js
Labels: bug

#4382 Add function to update browser bar URL
  nicegui/functions/navigate.py
  nicegui/testing/user_navigate.py
  website/documentation/content/doc/api.py
  website/documentation/content/navigate_documentation.py
Labels: enhancement

#4449 Better support select element with multiple values and dictionaries in user simulation
  nicegui/element_filter.py
  nicegui/testing/user_interaction.py
  tests/test_user_simulation.py
Labels: enhancement

#4522 Fix tests folder structure in project_structure_documentation.py
  website/documentation/content/project_structure_documentation.py
Labels: documentation

#4510 Fix typing for ui.refreshable/ui.refreshable_method
  nicegui/functions/refreshable.py
Labels: bug

#4537 let add_css, add_scss and add_sass set shared=True
  nicegui/functions/style.py
Labels: enhancement

#4544 Background-remove the screenshot for dark mode
  screenshot.png
Labels: documentation

#4507 modulepreload the scripts needed for faster page load
  nicegui/client.py
  nicegui/dependencies.py
  nicegui/templates/index.html
Labels: feature, review, 🟡 medium, 🌿 intermediate

#4551 use background_tasks.create over bare asyncio.create_task
  nicegui/page.py
Labels: bug, review, 🟠 major, 🌿 intermediate

#4553 Show On Air connection errors with message from server
  nicegui/air.py
Labels: feature, review, 🟡 medium
