Repository zauberzeug/nicegui, pull requests merged in 2025-05, with the labels that each got.

#4696 Document how to update context menu items
  website/documentation/content/context_menu_documentation.py
Labels: documentation, review, 🌱 beginner

#4702 Fix multi-cursor updates in `ui.codemirror`
  nicegui/elements/codemirror.py
  tests/test_codemirror.py
Labels: bug, 🟠 major

#4679 Add HTTPS protocol support to `ui.run`
  nicegui/helpers.py
  nicegui/ui_run.py
  nicegui/welcome.py
  tests/test_helpers.py
  website/documentation/content/section_configuration_deployment.py
Labels: feature, review

#4683 run.py: little refactoring to gain basic android compatibility
  nicegui/run.py
Labels: feature, review, 🟠 major

#4688 Sitewide index for AI
  website/documentation/code_extraction.py
  website/documentation/demo.py
  website/documentation/search.py
Labels: feature, review, 🌱 beginner

#4707 Image and Video Overlays in Leaflet API
  nicegui/elements/leaflet.py
  nicegui/elements/leaflet_layers.py
  nicegui/static/nicegui.css
  website/documentation/content/leaflet_documentation.py
Labels: feature, review, 🌿 intermediate

#4682 Add context manager to the user fixture
  nicegui/testing/user.py
  tests/test_user_simulation.py
  website/documentation/content/user_documentation.py
Labels: testing, review

#4678 fix `ui.codemirror` on JS UTF-16-based indexing (memoize JS length per char + bisect)
  nicegui/elements/codemirror.py
  tests/test_codemirror.py
Labels: bug, review, 🌳 advanced

#4692 Use the Mermaid API directly to fix nested diagram inside `ui.dialog`
  nicegui/elements/mermaid.js
Labels: bug, review, 🌳 advanced

#4724 Improve On Air reconnect behavior
  nicegui/air.py
Labels: bug, review, 🟠 major

#4725 Avoid KeyErrors caused by late `ui.run_javascript` responses
  nicegui/javascript_request.py
Labels: bug, review

#4727 docs: download functions added in 2.14.0
  nicegui/functions/download.py
Labels: documentation, review, ⚪️ minor, 🌱 beginner

#4733 Let npm.py run on Windows as well (hopefully same function as old)
  npm.py
Labels: infrastructure, review, ⚪️ minor, 🌱 beginner

#4722 Use Mermaid API directly to fix nested diagram inside `ui.dialog` inside `ui.markdown`
  nicegui/elements/markdown.js
  nicegui/static/nicegui.css
  tests/test_markdown.py
Labels: bug, review, 🌿 intermediate

#4170 Mermaid markdown documentation & visualization enhancement
  website/documentation/content/markdown_documentation.py
Labels: documentation, review

#4732 Show the documentation hierarchy in the sidebar
  main.py
  website/documentation/__init__.py
  website/documentation/rendering.py
  website/documentation/tree.py
  website/style.py
Labels: documentation, feature, review, 🟡 medium, 🌿 intermediate

#4754 Delay emitter until NiceGUI-level handshake done
  nicegui/static/nicegui.js
Labels: bug, review, ⚪️ minor

#4750 `log.push` support `classes`, `style`, and `props`
  nicegui/elements/log.py
  tests/test_log.py
  website/documentation/content/log_documentation.py
Labels: feature, review, ⚪️ minor

#4766 Remove Prometheus tracking
  fly.dockerfile
  fly.toml
  main.py
  prometheus.py
  release.dockerfile
Labels: infrastructure

#4539 Cachebusting via include timestamp into SHA256
  nicegui/dependencies.py
  nicegui/element.py
  nicegui/helpers.py
Labels: feature, review, 🟡 medium, 🌿 intermediate

#4757 Document use of user fixture with ui.select
  nicegui/testing/user_interaction.py
  tests/test_select.py
  tests/test_user_simulation.py
  website/documentation/content/user_documentation.py
Labels: bug, documentation, testing, review, 🟠 major

#4775 Let `ui.table.from_pandas` handle dataframes with lists or intervals
  nicegui/elements/table.py
Labels: bug, review, ⚪️ minor

#4769 Use Plausible Analytics on nicegui.io
  fly.dockerfile
  main.py
  website/documentation/rendering.py
  website/header.py
  website/imprint_privacy.py
  website/main_page.py
Labels: documentation, review

#4689 feat: generalize js_handler
  nicegui/element.py
  nicegui/static/nicegui.js
  tests/test_events.py
  website/documentation/content/element_documentation.py
Labels: feature, review, 🟠 major

#4789 Eliminating the warning: "<string>:27: (WARNING/2) Inline literal sta…
  nicegui/element.py
Labels: bug, documentation, review, ⚪️ minor

#4788 Get ruff happy after tightning the single-quote rules
  nicegui/client.py
  nicegui/elements/mixins/value_element.py
  nicegui/slot.py
  nicegui/storage.py
  tests/test_link.py
  tests/test_serving_files.py
Labels: infrastructure, ⚪️ minor

#4799 Preload only documentation pages marked with `@doc.auto_execute`
  website/documentation/content/doc/__init__.py
  website/documentation/content/doc/api.py
  website/documentation/content/element_filter_documentation.py
  website/documentation/content/link_documentation.py
  website/documentation/content/page_documentation.py
  website/documentation/content/page_layout_documentation.py
  website/documentation/content/refreshable_documentation.py
  website/documentation/content/section_pages_routing.py
Labels: bug, documentation, review

#4798 Defer non-critical JS for slightly faster page load under CPU+Network simultaneous bottleneck
  nicegui/templates/index.html
Labels: feature, review, ⚪️ minor

#4801 Skip ES module shim for modern browsers entirely, ~10% faster page load (CPU-bound)
  nicegui/templates/index.html
Labels: feature, review, ⚪️ minor

#4778 Introduce "Dynamic Resources" for robust inclusion of `codehilite.css` against match-all `@ui.page("/{_:path}")`
  nicegui/dependencies.py
  nicegui/element.py
  nicegui/elements/markdown.js
  nicegui/elements/markdown.py
  nicegui/nicegui.py
  tests/test_endpoint_docs.py
Labels: bug, review, 🟠 major

#4779 Warn if non-relative, since cross-origin download has many problems
  nicegui/functions/download.py
  website/documentation/content/download_documentation.py
Labels: feature, review
