Repository zauberzeug/nicegui, pull requests merged in 2025-10, with the labels that each got.

#5205 Use poetry 2.1.2 in the devcontainer
  .devcontainer/Dockerfile
Labels: infrastructure

#5204 Re-run `poetry lock` to fix `nicegui-highcharts` incompatibility
  poetry.lock
Labels: infrastructure

#5209 Check disabled state before clicking or clearing via user simulated interaction in pytests
  CHANGELOG.md
  nicegui/testing/user_interaction.py
  tests/test_user_simulation.py
Labels: testing, review

#5184 Make user.should_see work with ui.icon
  CHANGELOG.md
  nicegui/element_filter.py
  tests/test_user_simulation.py
Labels: testing, review

#5212 Fix ui.notify documentation link
  website/documentation/content/overview.py
Labels: documentation, review

#5214 Fix support for Redis Unix-Domainsocket-connections
  nicegui/persistence/redis_persistent_dict.py
Labels: bug, review
