Repository zauberzeug/nicegui, pull requests merged in 2025-09, with the labels that each got.

#5104 Use `str.translate` instead of repeated `str.replace` where possible
  nicegui/client.py
Labels: feature, review

#5107 Introduce Event class for sending events between different parts of the code
  nicegui/__init__.py
  nicegui/event.py
  nicegui/testing/general_fixtures.py
  tests/test_event.py
  website/documentation/content/event_documentation.py
  website/documentation/content/section_action_events.py
Labels: feature, review

#5108 Remove unnecessary attribute bindings
  nicegui/elements/dialog.js
  nicegui/elements/editor.js
  nicegui/elements/header.js
  nicegui/elements/image.js
  nicegui/elements/select.js
  nicegui/elements/table.js
Labels: bug, review, 🟠 major

#5112 `ui.log` multiline-push scroll-to-bottom via component approach
  nicegui/elements/log.js
  nicegui/elements/log.py
Labels: bug, review, 🟡 medium

#5143 `ui.aggrid` do not error out if no onGridReady
  nicegui/elements/aggrid.js
Labels: bug

#5145 Close sub_pages render coroutine on cancellation
  nicegui/elements/sub_pages.py
  tests/test_sub_pages.py
Labels: bug

#5116 Support client connection when Chrome performs speculative loading
  nicegui/background_tasks.py
  nicegui/client.py
  nicegui/elements/leaflet/leaflet.py
  nicegui/elements/timer.py
  nicegui/event.py
  nicegui/functions/javascript.py
  nicegui/page.py
  nicegui/static/nicegui.js
  nicegui/timer.py
  tests/test_page.py
  tests/test_speculative_loading.py
Labels: feature, review, 🌳 advanced

#5173 Call lifecycle event handlers more consistently
  nicegui/app/app.py
  nicegui/client.py
  tests/test_lifecycle.py
  website/documentation/content/overview.py
  website/documentation/content/section_action_events.py
Labels: feature, review

#5182 Persisting on teardown fails on 3.9
  nicegui/background_tasks.py
  tests/test_background_tasks.py
  tests/test_storage.py
Labels: bug, review
