Repository zauberzeug/nicegui, pull requests merged in 2025-02, with the labels that each got.

#4291 Filter keyboard events by type to ignore autocompletion
  nicegui/elements/keyboard.js
Labels: bug

#4299 Add to `redis.from_url` connection parameters
  nicegui/persistence/redis_persistent_dict.py
Labels: enhancement

#4285 Only delete page content if the number of connections is zero
  nicegui/air.py
  nicegui/client.py
  nicegui/nicegui.py
  nicegui/static/nicegui.js
  nicegui/testing/user.py
Labels: bug

#4303 Fix upload to zenodo by using our own built version
  .github/workflows/citation.yml
Labels: github_actions

#4317 Improve the update mechanism for `ui.plotly`
  nicegui/elements/plotly.py
  nicegui/elements/plotly.vue
Labels: bug

#4122 Automatic unregistering of `BindableProperty` objects
  nicegui/binding.py
  tests/test_binding.py
Labels: bug

#4360 Add Leaflet WMS support
  nicegui/elements/leaflet.js
  nicegui/elements/leaflet.py
  nicegui/elements/leaflet_layers.py
  website/documentation/content/leaflet_documentation.py
Labels: enhancement

#4324 Add zh-CN & zh-TW support when server down.
  nicegui/client.py
  nicegui/templates/index.html
  nicegui/translations.py
Labels: enhancement

#4347 Introduce QRating element
  nicegui/elements/rating.py
  nicegui/ui.py
  tests/test_rating.py
  website/documentation/content/rating_documentation.py
  website/documentation/content/section_controls.py
Labels: enhancement

#4379 improve update of notifications
  nicegui/elements/notification.js
  nicegui/elements/notification.py
  tests/test_notification.py
Labels: bug

#4251 Copyable classes with bindable properties
  nicegui/binding.py
  tests/test_binding.py
Labels: enhancement

#4355 Run init of app.storage.general as early as possible
  nicegui/app/app.py
  nicegui/nicegui.py
  nicegui/persistence/file_persistent_dict.py
  nicegui/persistence/persistent_dict.py
  nicegui/persistence/redis_persistent_dict.py
Labels: bug
